### ISSUE TITLE
return error in huge file

### ISSUE THREAD

**Issue by sinazahed** [aminyazdanpanah/PHP-FFmpeg-video-streaming#100]
hi im using this package with laravel and i convert them to hls with laravel job but it returns error when the file is big and job fails . 

i checked php_executaion_time and job and ffmpeg --timeout but all of them are correct in my case when the file is more than 150(MB) it returns a error . 

but when i reduce the size of that movie to 100(MB) every thing is ok .

ffmpeg failed to execute command /usr/bin/ffmpeg/ '-y' -i input.mp4 -c:v libx264 -c -a ...............

is there a limitation for file size ? or something else ? what should i check  ?

**Desktop/Server (please complete the following information):**
 - OS: ubuntu
 - Version 19.10
 - FFmpeg vesion [e.g. 4.1.6]

**Comment by angeljunior** [comment]
if your use php cli, change in php.ini memory_limit to -1

**Comment by aminyazdanpanah** [comment]
No. there is no limitation for file size. Check out your Laravel log. Maybe Laravel Job has a timeout attribute.
