### ISSUE TITLE
How to disable default representation?

### ISSUE THREAD

**Issue by adis0308** [aminyazdanpanah/PHP-FFmpeg-video-streaming#102]
How to convert an mp4 video with 1080p resolution to 720p hls only?
I used the addrepresentation as in the documentation but the results were 720p and 1080p.

**Comment by angeljunior** [comment]
I'm having the same problem, if the original file has higher resolution than what I indicated, it will make the original file plus the ones I added and not limit the ones I added.

**Comment by aminyazdanpanah** [comment]
See #49, #52
