### ISSUE TITLE
How do I add the -preset veryfast parameter when creating an HLS video?

### ISSUE THREAD

**Issue by chmerev** [aminyazdanpanah/PHP-FFmpeg-video-streaming#103]
When creating an HLS video.

https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming#hls

I want to add a parameter **- preset veryfast**, how do I do that?

**Comment by aminyazdanpanah** [comment]
Use [ `setAdditionalParams`](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/847d30e282ae41b389b88795ddb5010f8b900b59/src/Streaming.php#L48) method

**Comment by chmerev** [comment]
Thanks 🙏
