### ISSUE TITLE
How to convert just only one HLS video from video input with origianal file

### ISSUE THREAD

**Issue by sdtsoftwave** [aminyazdanpanah/PHP-FFmpeg-video-streaming#108]
I want convert video MP4 to HLS, but i received too many files. While I only need one file m3u8 with the original ratio of the video uploaded. 
Upload video.mp4 just receive video.m3u8 Not video_360p, video_720p, video_1080p and all .ts file.
Please help me do it. Thank you!

**Comment by aminyazdanpanah** [comment]
See #40, #49, #52
