### ISSUE TITLE
Uncaught Error: Class 'Representation' -> addRepresentation Function 

### ISSUE THREAD

**Issue by talaysa** [aminyazdanpanah/PHP-FFmpeg-video-streaming#11]
Hi,
I'm getting error when i try different representation add. My PHP Version is 7.3.8. I tried with different php versions but still same. Can you please check?

Here is my code,
`
require_once 'assets/vendor/autoload.php';

$config = [
    'ffmpeg.binaries'  => 'assets/extentions/FFmpeg/bin/ffmpeg.exe',
    'ffprobe.binaries' => 'assets/extentions/FFmpeg/bin/ffprobe.exe',
    'timeout'          => 3600, // The timeout for the underlying process
    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
];

$format = new Streaming\Format\X264();
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage% is transcoded\n";
});

$rep_1 = (new Representation())->setKiloBitrate(1000)->setResize(1080 , 720);
$rep_2 = (new Representation())->setKiloBitrate(500)->setResize(640 , 360);
$rep_3 = (new Representation())->setKiloBitrate(200)->setResize(480 , 270);

$ffmpeg = Streaming\FFMpeg::create($config)
->open('short.mp4') // the path to the video
->HLS()
->addRepresentation($rep_1) // Add a representation
->addRepresentation($rep_2) // Add a representation
->addRepresentation($rep_3) // Add a representation
->setHlsTime(20)
->setFormat($format)
->setHlsAllowCache(false)
->save();
`

Error Message,
Fatal error: Uncaught Error: Class 'Representation' not found in

**Comment by aminyazdanpanah** [comment]
Thank you for your reporting. 
I have just fixed [the bug](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/commit/1b97a3b841864c730ddb64cc6f3eef06052b5834) and now you need to update the package:

``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```

Also, you must set format first and use full namespace of `Streaming\Representation` (or you can use it in your script):

``` php 
use Streaming\Representation;
```

Try the code below:

``` php
require_once 'assets/vendor/autoload.php';

use Streaming\Representation;

$config = [
    'ffmpeg.binaries' => 'assets/extentions/FFmpeg/bin/ffmpeg.exe',
    'ffprobe.binaries' => 'assets/extentions/FFmpeg/bin/ffprobe.exe',
    'timeout' => 3600, // The timeout for the underlying process
    'ffmpeg.threads' => 12, // The number of threads that FFMpeg should use
];

$format = new Streaming\Format\X264();
$format->on('progress', function ($video, $format, $percentage) {
    echo "$percentage% is transcoded\n";
});

$rep_1 = (new Representation())->setKiloBitrate(1000)->setResize(1080, 720);
$rep_2 = (new Representation())->setKiloBitrate(500)->setResize(640, 360);
$rep_3 = (new Representation())->setKiloBitrate(200)->setResize(480, 270);

$ffmpeg = Streaming\FFMpeg::create($config)
    ->open('short.mp4')// the path to the video
    ->HLS()
    ->setFormat($format)
    ->addRepresentation($rep_1)// Add a representation
    ->addRepresentation($rep_2)// Add a representation
    ->addRepresentation($rep_3)// Add a representation
    ->setHlsTime(20)
    ->setHlsAllowCache(false)
    ->save();
```

**Comment by talaysa** [comment]
Thank you for quick response, it's working great now!

**Comment by talaysa** [comment]
Hi Amin,
Sorry my bad, i had tried again with autoRepresentation, i just noticed, it has still issue with custom presentation.

New error,

`Fatal error: Uncaught Streaming\Exception\Exception: Format has not been set in E:\AppServ\htdocs\test\ffmpeg\vendor\aminyazdanpanah\php-ffmpeg-video-streaming\src\Traits\Representation.php:31 Stack trace: #0 E:\AppServ\htdocs\test\ffmpeg\index.php(29): Streaming\HLS->addRepresentation(Object(Streaming\Representation)) #1 {main} thrown in E:\AppServ\htdocs\test\ffmpeg\vendor\aminyazdanpanah\php-ffmpeg-video-streaming\src\Traits\Representation.php on line 31`

**Comment by aminyazdanpanah** [comment]
First, you must add the  `setFormat()` method (or you can use `X264()`, `HEVC()`, `VP9()` alternatively) to the object, then you can add representations.

Try the code below:
``` php
require_once 'assets/vendor/autoload.php';

$config = [
    'ffmpeg.binaries' => 'assets/extentions/FFmpeg/bin/ffmpeg.exe',
    'ffprobe.binaries' => 'assets/extentions/FFmpeg/bin/ffprobe.exe',
    'timeout' => 3600, // The timeout for the underlying process
    'ffmpeg.threads' => 12, // The number of threads that FFMpeg should use
];

$ffmpeg = Streaming\FFMpeg::create($config)
    ->open('short.mp4')
    ->X264() // first set the format
    ->autoGenerateRepresentations() // then add representations
    ->save();
```

**Comment by talaysa** [comment]
It worked when i move format line before addRepresentation, thank you!
