### ISSUE TITLE
The code is a shame

### ISSUE THREAD

**Issue by colshrapnel** [aminyazdanpanah/PHP-FFmpeg-video-streaming#110]
https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/847d30e282ae41b389b88795ddb5010f8b900b59/src/File.php#L67

You are silencing the actual error, substituting it with a useless stub that cannot help to investigate and fix the problem.

**Comment by aminyazdanpanah** [comment]
If you have any suggestions send a pull request.
