### ISSUE TITLE
Please support PHP-FFMpeg version to 0.19.0

### ISSUE THREAD

**Issue by lonely2099** [aminyazdanpanah/PHP-FFmpeg-video-streaming#114]
PHP-FFMpeg 0.19.0 has been optimized in some details. Can you upgrade the version?

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I have just fixed the bug and now you can update the package:

```bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
