### ISSUE TITLE
mkv file not encode.

### ISSUE THREAD

**Issue by Navdeepsinh6699** [aminyazdanpanah/PHP-FFmpeg-video-streaming#12]
Hello Sir,
i had use your repository for encoding videos, major file types are supported but mkv files are not supported.
it will show error like below.

An uncaught Exception was encountered
Type: Streaming\Exception\Exception

Message: Invalid stream

Filename: C:\wamp64\www\codeigniter\encode_test\vendor\aminyazdanpanah\php-ffmpeg-video-streaming\src\AutoRepresentations.php

Line Number: 59

Backtrace:

File: C:\wamp64\www\codeigniter\encode_test\vendor\aminyazdanpanah\php-ffmpeg-video-streaming\src\AutoRepresentations.php
Line: 70
Function: getKiloBitRate

File: C:\wamp64\www\codeigniter\encode_test\vendor\aminyazdanpanah\php-ffmpeg-video-streaming\src\Traits\Representation.php
Line: 57
Function: get

File: C:\wamp64\www\codeigniter\encode_test\application\controllers\Welcome.php
Line: 49
Function: autoGenerateRepresentations

File: C:\wamp64\www\codeigniter\encode_test\index.php
Line: 316
Function: require_once

**my code is below**
````
$config = [
		   	'ffmpeg.binaries'  => MYPATH.'ffmpeg.exe', // the path to the FFMpeg binary
            'ffprobe.binaries' => MYPATH.'ffprobe.exe', // the path to the FFProbe binary
		    'timeout'          => 3600000, // The timeout for the underlying process
		    'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
		    ];
		    
		$ffmpeg = Streaming\FFMpeg::create($config);
		
		$format = new Streaming\Format\X264();

		$format->on('progress', function ($video, $format, $percentage) {
		    echo "</br>$percentage% is transcoded\n";
		});

		$ffmpeg
		    ->open(MYPATH.'output\\sample.mkv')
		    ->HLS()
		    ->setFormat($format)
		    ->autoGenerateRepresentations([1080, 480, 360])
		    ->save(MYPATH.'output\\samplenew\\sample.m3u8');
````

i don't know how to fix pls help.
Thankx in Advance.

**Comment by aminyazdanpanah** [comment]
`Matroska(MKV)` format does not store some parameters such as frame rate and bit rate in its container. So [FFprobe](https://ffmpeg.org/ffprobe.html) cannot obtain the value of these params and as a result, this package cannot set the value of `setKiloBitrate` to create representations.

I will try to find a solution for this issue and hopefully fix it in the next release, but until then, you can add representations manually:
``` php
use Streaming\Representation;

$config = [
    'ffmpeg.binaries' => MYPATH . 'ffmpeg.exe', // the path to the FFMpeg binary
    'ffprobe.binaries' => MYPATH . 'ffprobe.exe', // the path to the FFProbe binary
    'timeout' => 3600000, // The timeout for the underlying process
    'ffmpeg.threads' => 12,   // The number of threads that FFMpeg should use
];

$ffmpeg = Streaming\FFMpeg::create($config);

$format = new Streaming\Format\X264();

$format->on('progress', function ($video, $format, $percentage) {
    echo "</br>$percentage% is transcoded\n";
});

$rep_1 = (new Representation())
    ->setKiloBitrate(REPLACE_WITH_YOUR_OWN_KILOBITE_RATE)
    ->setResize(REPLACE_WITH_YOUR_OWN_WIDTH, 1080);
$rep_2 = (new Representation())
    ->setKiloBitrate(REPLACE_WITH_YOUR_OWN_KILOBITE_RATE)
    ->setResize(REPLACE_WITH_YOUR_OWN_WIDTH, 480);
$rep_3 = (new Representation())
    ->setKiloBitrate(REPLACE_WITH_YOUR_OWN_KILOBITE_RATE)
    ->setResize(REPLACE_WITH_YOUR_OWN_WIDTH, 360);

$ffmpeg
    ->open(MYPATH . 'output\\sample.mkv')
    ->HLS()
    ->setFormat($format)
    ->addRepresentation($rep_1)
    ->addRepresentation($rep_2)
    ->addRepresentation($rep_3)
    ->save(MYPATH . 'output\\samplenew\\sample.m3u8');
```

Alternatively, you can convert your videos to `mp4` format using FFmpeg and try to package the converted video. (It will take too long and I do not recommend it)
``` php
use FFMpeg\Format\Video\X264;
$ffmpeg
    ->open(MYPATH . 'output\\sample.mkv')
    ->save(new X264(), MYPATH . 'output\\sample.mp4');
```

**Comment by Navdeepsinh6699** [comment]
Thank you its work proper.

**Comment by Navdeepsinh6699** [comment]
Ok Sir , its working proper. *Thank You*
But now i have another issue. unfortunately encode stop. following error
will display.
An uncaught Exception was encountered

Type: FFMpeg\Exception\RuntimeException

Message: Encoding failed

Filename:
/home/mamimovies/public_html/mami_movies/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php

Line Number: 106

Backtrace:

File:
/home/mamimovies/public_html/mami_movies/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Media.php
Line: 82
Function: call_user_func_array

File:
/home/mamimovies/public_html/mami_movies/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Export.php
Line: 59
Function: __call

File:
/home/mamimovies/public_html/mami_movies/application/controllers/Convert.php
Line: 50
Function: save

File: /home/mamimovies/public_html/mami_movies/index.php
Line: 292
Function: require_once
*I have large file for i.g more then 1GB*
*My current code is following.*

$filename= 'kasoor.mp4';

" $v11=FCPATH.'assets/images/VCMobile/kasoor/'.$filename;
$foldername = pathinfo($filename, PATHINFO_FILENAME);
$newfile = FCPATH .
'assets/images/VCMobile/'.$foldername.'/Leikhamton.m3u8';

$config = [
        'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
        'ffprobe.binaries' => '/usr/bin/ffprobe',
        'timeout'          => 0, // The timeout for the underlying process
        'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg
should use
        ];

        $ffmpeg = Streaming\FFMpeg::create($config);

        $video = $ffmpeg->open($v11);

        $rep_2 = (new
Representation())->setKiloBitrate(1024)->setResize(640 , 360);
        $video->HLS()
            ->X264()
            ->setHlsTime(10)
            ->addRepresentation($rep_2)
            ->setHlsAllowCache(false)
            ->save();

        echo "success";
        exit; "

i did't find any solution pls help me.

Thank You.
