### ISSUE TITLE
Too long to convert mp4 -> hls

### ISSUE THREAD

**Issue by MobileheadSherman** [aminyazdanpanah/PHP-FFmpeg-video-streaming#122]
Hello 
I m using your library for building video streaming service but too long to converting mp4 -> hls
How to improve and make it faster ?
Please help me. Thanks

**Comment by khasandesign** [comment]
@MobileheadSherman  Facing the same issue, did you find any solution?

**Comment by aminyazdanpanah** [comment]
It depends on your hardware resources and how much resource are dedicated to the transcoding process.

**Comment by MobileheadSherman** [comment]
I used VPS (good performance AWS EC2 Medium)
