### ISSUE TITLE
Add support for PHP-FFMpeg/PHP-FFMpeg 1.x

### ISSUE THREAD

**Issue by andrewg211** [aminyazdanpanah/PHP-FFmpeg-video-streaming#123]
Hi There,

Do you have any plans to add support for PHP-FFMpeg/PHP-FFMpeg 1.x versions.

Thanks mate.

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I have just released the new version and now you can update the package:

```bash
composer require aminyazdanpanah/php-ffmpeg-video-streaming
```
