### ISSUE TITLE
Support for  subtitles via mpeg-dash 

### ISSUE THREAD

**Issue by shimonewman** [aminyazdanpanah/PHP-FFmpeg-video-streaming#124]
Hey there,
Do you have any plans on supporting
subtitles via MPEG-DASH?

**Comment by aminyazdanpanah** [comment]
Unfortunately, no. But you can use [Shaka PHP](https://github.com/aminyazdanpanah/shaka-php) which is great for this use case (see [this example](https://github.com/aminyazdanpanah/shaka-php/blob/master/examples/dash/on-demand.php)).
