### ISSUE TITLE
Large File not encoded 

### ISSUE THREAD

**Issue by Navdeepsinh6699** [aminyazdanpanah/PHP-FFmpeg-video-streaming#14]
My previous issue regarding to mkv extensions is solved. Thank you.
But now i have another issue. unfortunately encode stop. following error
will display.
An uncaught Exception was encountered

**Type: FFMpeg\Exception\RuntimeException**

**Message: Encoding failed**

Filename:
/home/mamimovies/public_html/mami_movies/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php

Line Number: 106

Backtrace:

File:
/home/mamimovies/public_html/mami_movies/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Media.php
Line: 82
Function: call_user_func_array

File:
/home/mamimovies/public_html/mami_movies/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Export.php
Line: 59
Function: __call

File:
/home/mamimovies/public_html/mami_movies/application/controllers/Convert.php
Line: 50
Function: save

File: /home/mamimovies/public_html/mami_movies/index.php
Line: 292
Function: require_once

***I have large file for i.g more then 1GB***
***My current code is following**.*

 ```
$filename= 'kasoor.mp4';
 $v11=FCPATH.'assets/images/VCMobile/kasoor/'.$filename;
 $foldername = pathinfo($filename, PATHINFO_FILENAME);
 $newfile = FCPATH .'assets/images/VCMobile/'.$foldername.'/Leikhamton.m3u8';
 $config = [
        'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
        'ffprobe.binaries' => '/usr/bin/ffprobe',
        'timeout'          => 0, // The timeout for the underlying process
        'ffmpeg.threads'   => 12,   // The number of threads that FFMpeg should use
   ];
   $ffmpeg = Streaming\FFMpeg::create($config);
   $video = $ffmpeg->open($v11);
   $rep_2 = (new Representation())->setKiloBitrate(1024)->setResize(640 , 360);
   $video->HLS()
            ->X264()
            ->setHlsTime(10)
            ->addRepresentation($rep_2)
            ->setHlsAllowCache(false)
            ->save();
  echo "success";
  exit; 

```

I did't find any solution pls help me.
Thank You.

**Comment by aminyazdanpanah** [comment]
Try to change the following code in `/home/mamimovies/public_html/mami_movies/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/AbstractVideo.php`  on line 106:

``` php
if (null !== $failure) {
    throw new RuntimeException('Encoding failed', $failure->getCode(), $failure);
}
```

To:
``` php
if (null !== $failure) {
    throw new RuntimeException($failure->getMessage(), $failure->getCode(), $failure);
}
```

After that, run the code again to see the command that executes in your server/computer.

You will get an error like this:

``` text
Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command: /usr/bin/ffmpeg -y -i /path/to/file/kasoor.mp4 ...
```

The command is:
``` bash
/usr/bin/ffmpeg -y -i /path/to/file/kasoor.mp4 ...
```

Try to execute the command in your terminal(or command prompt) to see the **FFmpeg error**.

In the end, reverse the code you have changed.

I cannot help you with such little provided information. Sorry!

**Comment by Navdeepsinh6699** [comment]
Thank you form informs its help.
