### ISSUE TITLE
Tvheadend or similar input

### ISSUE THREAD

**Issue by DanielQuirogaDev** [aminyazdanpanah/PHP-FFmpeg-video-streaming#15]
Hi!

Thanks for the wonderful library,

i am working in a streaming project and getting input via tvheadend, then i have to stream it again using rtp protocol:

 ffmpeg  -i "http://@localhost:9981/stream/channelid/556832578"  -vcodec libx264  -vb 500k -vprofile baseline -acodec mp2  -ac 2 -f rtp_mpegts rtp://192.168.99.205:1001

I don't think the video wrapper will be a problem, but the "rtp_mpegts" part worries me a little bit.

**Comment by aminyazdanpanah** [comment]
I am glad that you like this project. This project does not support Real-time Protocols yet. 

Unfortunately, I do not have access to [Tvheadend](https://tvheadend.org/) but I have just tested your command with an RTP URL test and your command is totally fine.

``` bash 
ffmpeg -i rtp://@239.0.0.1:5004 -vcodec libx264 -vb 500k -vprofile baseline -acodec mp2 -ac 2 -f rtp_mpegts rtp://@239.0.0.1:1001
```

I played the stream with `ffplay`:
``` bash
ffplay rtp://@239.0.0.1:1001
```
