### ISSUE TITLE
setMediaInfoBinary Usage Example

### ISSUE THREAD

**Issue by talaysa** [aminyazdanpanah/PHP-FFmpeg-video-streaming#17]
Hi,
How can i bypass MediaInfo path with setMediaInfoBinary? When i call function from Streaming\MediaInfo, it is showing error for other variables? 
Can you give usage example setMediaInfoBinary?

Thanks,
Salih

**Comment by aminyazdanpanah** [comment]
You can set the `setMediaInfoBinary` method after you open a file.
Try the following code:

``` php
$streams = Streaming\FFMpeg::create()
    ->open('/path/to/file')
    ->setMediaInfoBinary('/path/to/mediainfo/cli')
    ->mediaInfo();

$general = $streams->general();
$video = $streams->videos()->first();
$audio = $streams->audios()->first();

var_dump($general->all(), $video->all(), $audio->all());
```

You can also add the directory of [MediaInfo CLI](https://mediaarea.net/en/MediaInfo) to your system path and this package auto-detect the MediaInfo binary.
