### ISSUE TITLE
[Question] Convert MP4 to HLS without transcoding

### ISSUE THREAD

**Issue by kfeng0806** [aminyazdanpanah/PHP-FFmpeg-video-streaming#19]
Hello,
I am trying to split mp4 to HLS without generate other representations just keep original encoding.
If use without `autoGenerateRepresentations` i get error `Call to a member function getHeight() on bool`

**Comment by aminyazdanpanah** [comment]
It depends on what you mean by "keeping original encoding". If you mean the size of the video and its bitrate, then you can add a representation manually with the original size and bitrate.

``` php
use Streaming\Representation;

$rep = (new Representation())->setKiloBitrate(YOUR_VIDEO_KILO_BITRATE)->setResize(YOUR_VIDEO_WIDTH, YOUR_VIDEO_HEIGHT);

$video->HLS()
    ->X264()
    ->addRepresentation($rep)
    ->save();
```
 You must specify at least one representation to create HLS playlist and segments.

FFMpeg will decide to transcode the video or just breaking the content into a sequence of small HTTP-based file segments.

If you have any problems with running your code, please post it here.

**Comment by kfeng0806** [comment]
Thanks for your reply, and sorry for my unclear description.

My requirement just split MP4 video into HLS m3u8 instead encode the original video, your `shaka-php` package just solved my problem.

Thank you very much!
