### ISSUE TITLE
autoGenerateRepresentaions fails when using mediainfo < 18

### ISSUE THREAD

**Issue by sproutdebisa** [aminyazdanpanah/PHP-FFmpeg-video-streaming#20]
@aminyazdanpanah
the mediainfo package has to be the version that supports JSON output.
For example, I get this error when using mediainfo v17 on ubuntu 18.04.

@aminyazdanpanah  consider getting info from mediainfo in XML and then parse to JSON
https://pasteboard.co/IyRutWO.png

**Comment by aminyazdanpanah** [comment]
This method was deprecated and it has removed from the source code. This package does not use MediaInfo library anymore and you must update the package:
``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
