### ISSUE TITLE
Change Files Permission to Public in Digital Ocean Cloud

### ISSUE THREAD

**Issue by irfan0786** [aminyazdanpanah/PHP-FFmpeg-video-streaming#26]
**Describe the bug**
First of all thanks for the library. I'm facing one issue I'm uploading HLS in Digital Ocean Cloud but unfortunately files permission is private. How can I change it ? Please see below my code.

**Code**
```

$aws_cloud_upload_options = [
                    'dest' => $s3VideoPath,
                    'ACL'          => 'public-read'
                ];
                
                $to_aws_cloud = [
                    'cloud' => $aws_cloud,
                    'options' => $aws_cloud_upload_options
                ];

$ffmpegHLS = \Streaming\FFMpeg::create($config)
                    ->openFromCloud($from_aws_cloud)
                    ->HLS()
                    ->X264()
                    ->addRepresentation($rep_360)
                    ->addRepresentation($rep_480)
                    ->setHlsTime(5)
                    ->setHlsAllowCache(false);
                    $metadata = $ffmpegHLS->save(null, $to_aws_cloud);
```

**Comment by aminyazdanpanah** [comment]
I have never worked with **[Digital Ocean Cloud](https://cloud.digitalocean.com/)** or **[DigitalOcean API](https://developers.digitalocean.com/)**, so I do not know how to change the permission files, sorry. I suggest you **[contact them](https://cloudsupport.digitalocean.com/s/)** to help with that.

If you mean **[Amazon S3](https://aws.amazon.com/s3/)** (as your variable name is $aws), then you can set the ACL param to change the permission files to the public.

If you have any problem with running your code please post your cloud class($aws_cloud) code here.

**Comment by irfan0786** [comment]
Thanks for the quick response, I fixed it. Modified uploadDirectory Function.

**Updated Code**

```
public function uploadDirectory(string $dir, array $options): void
    {
        $dest = $options['dest'];

        try {
            $manager = new Transfer($this->s3, $dir, $dest, array(
                'concurrency' => 20,
                'debug'       => false,
                'before' => function (\Aws\Command $command) {
                    $command['ACL'] = 'public-read';
                }
            ));
            $manager->transfer();
        } catch (S3Exception $e) {
            throw new RuntimeException("There was an error downloading the file.\n error: " . $e->getMessage(), $e->getCode(), $e);
        }
    }
```
