### ISSUE TITLE
HLS h264_amf

### ISSUE THREAD

**Issue by codixor** [aminyazdanpanah/PHP-FFmpeg-video-streaming#27]
Hi,
trying to implement AMD encoding future with video codec h264_amf working good on PHP-FFMpeg/PHP-FFMpeg but i cant implement this on your code i tried to extend Streaming\Format\X264 to support 'h264_amf' but no effect sltill using only CPU to encode and also can we change Audiocodec to on hls streaming.

**Comment by aminyazdanpanah** [comment]
`Streaming\Format\X264` is a final class, so you cannot extend this class. Instead, you should extend `Streaming\Format\Video`  and create your own format class.

``` php
class MyFormat extends Streaming\Format\Video
{
    public function __construct($audioCodec=YOUR_AUDIO_CODEC, $videoCodec='h264_amf')
    {
        $this
            ->setAudioCodec($audioCodec)
            ->setVideoCodec($videoCodec);
    }

   // other functions...
}
```

After creating your own class, you should pass the object to the `setFormat` method
``` php 
$video->DASH()
    ->setFormat(new MyFormat())
    ->autoGenerateRepresentations()
    ->save();
``` 

if you have any problems with running your code, please post it here.

**Comment by codixor** [comment]
Hi,
sorry i made the test creating costum X264 class extends Video but same i think is related to 2 parts.

-First is -c:v in map for hls

`private function HLSFilter(HLS $hls)
    {
        $filter = [];
        $total_count = count($representations = $hls->getRepresentations());
        $counter = 0;
        $path_parts = $hls->getPathInfo();
        $dirname = str_replace("\\", "/", $path_parts["dirname"]);
        $filename = substr($path_parts["filename"], -100);
        $ts_sub_dir = Utilities::appendSlash($hls->getTsSubDirectory());
        $base_url = Utilities::appendSlash($hls->getHlsBaseUrl());
        if ($ts_sub_dir) {
            FileManager::makeDir($dirname . DIRECTORY_SEPARATOR . $ts_sub_dir);
            $base_url = $base_url . $hls->getTsSubDirectory() . "/";
        }
        foreach ($representations as $representation) {
            if ($representation instanceof Representation) {
                $filter[] = "-s:v";
                $filter[] = $representation->getResize();
                $filter[] = "-crf";
                $filter[] = "20";
                $filter[] = "-sc_threshold";
                $filter[] = "0";
                $filter[] = "-g";
                $filter[] = "48";
                $filter[] = "-keyint_min";
                $filter[] = "48";
                $filter[] = "-hls_list_size";
                $filter[] = "0";
                $filter[] = "-hls_time";
                $filter[] = $hls->getHlsTime();
                $filter[] = "-hls_allow_cache";
                $filter[] = (int)$hls->isHlsAllowCache();
                $filter[] = "-b:v";
                $filter[] = $representation->getKiloBitrate() . "k";
                $filter[] = "-maxrate";
                $filter[] = intval($representation->getKiloBitrate() * 1.2) . "k";
                $filter[] = "-hls_segment_filename";
                $filter[] = $dirname . "/" . $ts_sub_dir . $filename . "_" . $representation->getHeight() . "p_%04d.ts";
                if ($base_url) {
                    $filter[] = "-hls_base_url";
                    $filter[] = $base_url;
                }
                if ($hls->getHlsKeyInfoFile()) {
                    $filter[] = "-hls_key_info_file";
                    $filter[] = $hls->getHlsKeyInfoFile();
                }
                $filter[] = "-strict";
                $filter[] = $hls->getStrict();
                if (++$counter !== $total_count) {
                    $filter[] = $dirname . "/" . $filename . "_" . $representation->getHeight() . "p.m3u8";
                }
            }
        }
        return $filter;
    }`

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I have fixed [the bug](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/commit/c3717066ef2f0c1276631d060af3b6892d0e8112) and now you can update the package.

``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```

After updating the package, you can test the following code:
``` php
Streaming\FFMpeg::create()
    ->open(PATH_TO_VIDEO)
    ->HLS()
    ->X264('h264_amf')
    ->autoGenerateRepresentations()
    ->save();
```
