### ISSUE TITLE
Hosting Block with Example Video

### ISSUE THREAD

**Issue by talaysa** [aminyazdanpanah/PHP-FFmpeg-video-streaming#28]
Hi Amin,
I was working with your example via documantation. Your hosting blocked me. In default example you have one video from your hosting, i was using for my test case. Probably because of to many get request, it blocked. Now i can not access to documantation or your website :) 

Example video from documantion,
https://www.aminyazdanpanah.com/my_sweetie.mp4

Maybe you should change location of example video. And if you can refresh firewall, i would appreciate it.

Thanks,
Salih

**Comment by aminyazdanpanah** [comment]
I apologize for the inconvenience. Please send me your public IP address via contact@aminyazdanpanah.com to remove it from the blacklist IP. You can get your public IP address by searching "what is my ip" on Google.
https://www.google.com/search?q=what+is+my+ip

To avoid blocking your IP address from a host or a website, I suggest you use multiple sample videos. For example, in the website below, you can find some links of sample videos that are usable for your test:
https://file-examples.com/index.php/sample-video-files/sample-mp4-files/

You can find other websites by searching "[sample video](https://www.google.com/search?q=sample+video)" on Google.

NOTE: Please **BE CAREFUL** about malware and unsafe websites.

**Comment by talaysa** [comment]
No problem, actually i apologize for too much request :) Thank you so much, i'm sending now.
