### ISSUE TITLE
Encryption key rotation for TS 

### ISSUE THREAD

**Issue by ubheamar** [aminyazdanpanah/PHP-FFmpeg-video-streaming#29]
Hello,
First of all thanks for this awesome library.

I am looking something which encrypt HLS every ts file with with different key or using key rotation like zencoder have 
https://support.brightcove.com/zencoder-encoding-settings-encryption#encryption_key_rotation_period

is it possible in current library ? 
can you tell me which point in library  i can set keyinfo of hls class i will do it

**Comment by aminyazdanpanah** [comment]
According to the FFmpeg docs, `hls_flags periodic_rekey` should be enabled(see **[HLS options](https://ffmpeg.org/ffmpeg-formats.html#hls-2)**). So I just have [added the `setAdditionalParams`](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/commit/32f6b3a5c0d71c38f2602f456fb0815728a8fb1b) method to set this option. But before you get started, you need to update the package.
``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
After updating the package, you can set this option:
``` php
use Streaming\Representation;

$format = new Streaming\Format\X264();
$format->on('progress', function ($video, $format, $percentage){
    echo sprintf("\rTranscoding...(%s%%) [%s%s]", $percentage, str_repeat('#', $percentage), str_repeat('-', (99 - $percentage)));
});

$r_360p  = (new Representation)->setKiloBitrate(276)->setResize(640, 250);
$r_480p  = (new Representation)->setKiloBitrate(750)->setResize(854, 480);

Streaming\FFMpeg::create()
    ->open('path/to/video')
    ->HLS()
    ->setFormat($format)
    ->setAdditionalParams(['-hls_flags', 'periodic_rekey'])
    ->setHlsKeyInfoFile("path/to/keyinfo")
    ->addRepresentations([$r_480p, $r_360p])
    ->save();
```

To encrypt the stream with the new key/IV, please **Do not forget** to update the `keyinfo` file periodically, including the file containing the AES encryption key.

**Comment by ubheamar** [comment]
Hello thanks for quick reply but i am not able to figure out where can i update key periodically.

i was thinking to add event progress but i am not able to get stream object there.

can you please help me regarding this

**Comment by aminyazdanpanah** [comment]
"Updating the key info file" is not in the scope of this project, but you can create a script(in any language) to generate a new encryption key and update the key info file. For instance, the following code generates a new encryption key every 10 seconds(in php language):

**key_info_file_generator.php**
``` php
function updateKeyInfoFile(string $keu_info_path, string $key_path, string $url, int $length = 16): void
{
    if (!extension_loaded('openssl')) {
        throw new \Exception('OpenSSL is not installed.');
    }
    file_put_contents($key_path, openssl_random_pseudo_bytes($length));
    file_put_contents($keu_info_path, implode(PHP_EOL, [$url, $key_path, bin2hex(openssl_random_pseudo_bytes($length))]));
}
$i = 1;

while (true){
    $keu_info_path = sys_get_temp_dir() . DIRECTORY_SEPARATOR . $argv[1];
    $key_path = $argv[2] . "-" . $i . ".key";
    $url = $argv[3] . "-" . $i . ".key";;

    updateKeyInfoFile($keu_info_path, $key_path, $url);

    $i++;
    sleep(10);
}
```
To test it, run [this code](#issuecomment-569531454) again. At the same time, open a new terminal and run the script. (The script will run forever until you terminate it.) When FFmpeg has finished, terminate the script.

Run the example:
``` bash
php key_info_file_generator.php file.keyinfo mykey http://wwww.aminyazdanpanah.com/PATH_TO_KEY_DIRECTORY/mykey
```

You can also create an event to do this operation automatically. For more information please visit **[this page](https://www.php.net/manual/en/book.event.php)**.
