### ISSUE TITLE
Ideas about fmp4 (fragmented mp4s)

### ISSUE THREAD

**Issue by ryancwalsh** [aminyazdanpanah/PHP-FFmpeg-video-streaming#31]
Thank you so much for your very useful library.

I was wondering if you have any ideas about how to accomplish the following.

Currently I have:

```
class HlsVideo extends \Streaming\HLS {

    protected \Streaming\Filters\Filter $filter;

    public function getFilter(): \Streaming\Filters\Filter {
        return new HlsFilter($this);
    }

}
```

and
```
use Streaming\File;
use Streaming\HLS;
use Streaming\Representation;

class HlsFilter extends \Streaming\Filters\HLSFilter {

    const INIT_DOT_MP4 = "init.mp4";

    public function setFmp4Options(array &$filter, $dirname, $ts_sub_dir, array $path_parts, \Streaming\Representation $rep) {
        $filter[] = "-hls_segment_type";
        $filter[] = "fmp4";
        $filter[] = "-hls_fmp4_init_filename";
        $filter[] = $dirname . "/" . $ts_sub_dir . self::INIT_DOT_MP4;
        $filter[] = "-hls_segment_filename";
        $segmentsFilenamePattern = $dirname . "/" . $ts_sub_dir . $path_parts["filename"] . "_" . $rep->getHeight() . "p_%04d.m4s";
        $filter[] = $segmentsFilenamePattern;
    }
//... Then the rest of the class is nearly identical to \Streaming\Filters\HLSFilter but I couldn't just extend your class because you used private methods. So I copied and pasted most of your functions into my class, and then my function HLSFilter calls `$this->setFmp4Options($filter, $dirname, $ts_sub_dir, $path_parts, $rep);`
```

Then in a third class I call encryptVideo:

```
public function encryptVideo(string $inputFilename, string $outputFilename, string $keyInfoFilePath) {
    $log = new Logger('FFmpeg_Streaming');
    $log->pushHandler(new StreamHandler('storage/logs/ffmpeg-streaming.log'));
    $ffmpeg = FFMpeg::create($this->getConfig(), $log);
    $video = $ffmpeg->open($inputFilename);
    $format = new \Streaming\Format\X264();
    $representations = [$this->getOriginalRepresentation($video)];
    $hlsVideo = new HLS\HlsVideo($video);
    $hlsVideo
            ->setFormat($format)
            ->setHlsKeyInfoFile($keyInfoFilePath)
            ->addRepresentations($representations)
            ->setHlsAllowCache(false)
            ->save($outputFilename);
}

public function getOriginalRepresentation(Media $video): Representation {
    $firstVideoStream = $video->getStreams()->videos()->first();
    $width = $firstVideoStream->get('width');
    $height = $firstVideoStream->get('height');
    $kiloBitrate = $firstVideoStream->get('bit_rate') / self::KILO_MULTIPLIER;
    return (new Representation)->setResize($width, $height)
                    //->setAudioKiloBitrate($audioKiloBitrate)//Where can I retrieve the original audioKiloBitrate?
                    ->setKiloBitrate($kiloBitrate);
}
```
**This nearly works!**

It properly creates the m4s files, the m3u8 files, and the init.mp4 file. 

And then I use [hls.js](https://github.com/video-dev/hls.js/) on my webpage to try to show the video.

Initially, it won't load.

But then I can get the video to load properly if I refresh the page after making this edit to list_1080p.m3u8:

Change from:

`#EXT-X-MAP:URI="/myproject/public/storage/000000002/init.mp4"`

To:

`#EXT-X-MAP:URI="init.mp4"`

**What can I change so that ffmpeg knows the absolute path of where to save the init.mp4 but also knows to write in the m3u8 only the filename `init.mp4` without any path?**

And I'm curious if you have any suggestions about a better way to do what I've done so far; maybe there is a way to avoid copying and pasting your code.

And if you have ideas about my question above in the comment in getOriginalRepresentation, I'd love to hear, too.

Thanks so much. :-)

**Comment by aminyazdanpanah** [comment]
It seems like you pass the full path of the init segment file to this option. You should only pass the name of a file to this option(i.e `init.mp4`). 

I have just added some methods to this library to support the `fragmented MP4 format` and now you can update the package:
```
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
After updating the package, you can use the following code to create fragmented mp4 files:

``` php
$ffmpeg = Streaming\FFMpeg::create();
$video = $ffmpeg->open("path/to/video");

$hls = $video->HLS()
    ->setHlsSegmentType('fmp4')
    ->X264()
    ->autoGenerateRepresentations([]) // it only generate a representation(only original representation)
    ->save('path/to/master-playlist.m3u8');
```
If you pass an empty array to the `autoGenerateRepresentations` method, it generates only one representation(the highest biterate and the largest size).

If you want to retrieve the original audioKiloBitrate, you can use the following code:
``` php
public function getOriginalRepresentation(Media $video): Representation
{
    $firstVideoStream = $video->getStreams()->videos()->first();
    $firstAudioStream = $video->getStreams()->audios()->first();
    $width = $firstVideoStream->get('width');
    $height = $firstVideoStream->get('height');
    $kiloBitrate = $firstVideoStream->get('bit_rate') / self::KILO_MULTIPLIER;
    $audioKiloBitrate = $firstAudioStream->get('bit_rate') / self::KILO_MULTIPLIER;
    return (new Representation)->setResize($width, $height)
        ->setAudioKiloBitrate($audioKiloBitrate)
        ->setKiloBitrate($kiloBitrate);
}
```

**NOTE-1:** Some formats(such as MKV or Matroska) do not store some parameters such as frame rate and bit rate in their container. So you may not be able to retrieve this parameter.

**NOTE-2:** `fmp4` files may be used in HLS version 7 and above. (see **[HLS options](https://ffmpeg.org/ffmpeg-formats.html#hls-2)** and **[HLS Documentation](https://developer.apple.com/streaming/)** for more information)

**NOTE-3:** FFmpeg does not support Encrypted fmp4 yet. (it has not been implemented in FFmpeg yet)

**Comment by ryancwalsh** [comment]
Wow, thank you so much!

I'd already tried passing just init.mp4 instead of its absolute path, but then it saves init.mp4 to the wrong place. So it just changes what my problem is. 

Do you know of a way to change the initial working directory of ffmpeg before the command is run? I.e. `cd /outputdir/` before calling the ffmpeg command? If I could do that, then your approach of passing init.mp4 instead of its absolute path would work.

And I'd already tried using `->autoGenerateRepresentations([])`, but it created multiple representations instead of just what the original video was.

https://hlsbook.net/hls-fragmented-mp4/ seems to say that ffmpeg supports encrypted fmp4, right?

**Comment by ryancwalsh** [comment]
Actually I just deleted my getOriginalRepresentation and used your `->autoGenerateRepresentations([])` and I think that part did work. Thanks (Maybe in previous attempts I provided no arguments instead of an empty array.)

And I _think_ my encryption is working. The video and audio work.  I'm not really sure how to tell whether their files are encrypted. 

So I think my only remaining challenge is figuring out how to make the `#EXT-X-MAP:URI=` in the m3u8 just point to `"init.mp4"` without an absolute path (while still providing an absolute path to `-hls_fmp4_init_filename` so that the mp4 gets created in the correct place).

Or, like I mentioned above, I bet it would work if I could provide "init.mp4" to `-hls_fmp4_init_filename` (without absolute path) but first change the working directory of ffmpeg.

**Comment by aminyazdanpanah** [comment]
If I am not mistaken, you mean when you run the FFmpeg, the init file and segment files have different paths. they are not in the same directory. If it is wrong, could you post the content of your playlist manifest here? 

Because when I run the FFmpeg to create fmp4 files, all files created in the same directory.
 ```php
$save_to = "/home/public_html/PATH_TO_KEY_DIRECTORY/new.key";
$url = "https://www.aminyazdanpanah.com/PATH_TO_KEY_DIRECTORY/new.key";

$ffmpeg = Streaming\FFMpeg::create();
$video = $ffmpeg->open("path/to/video");

$hls = $video->HLS()
    ->setHlsSegmentType('fmp4')
    ->encryption($save_to, $url) // if your ffmpeg version is compatible with fmp4 encryption
    ->X264()
    ->autoGenerateRepresentations([]) 
    ->save('/var/www/test.m3u8');
```

**Output:**
```
/var/www/test.m3u8
/var/www/test_1080p.m3u8
/var/www/test_init.mp4
/var/www/test_1080p_0000.m4s
/var/www/test_1080p_0001.m4s
/var/www/test_1080p_0002.m4s
/var/www/test_1080p_0003.m4s
/var/www/test_1080p_0004.m4s
/var/www/test_1080p_0005.m4s
```

**test_1080p.m3u8**
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-MAP:URI="test_init.mp4"
#EXTINF:11.200000,
test_1080p_0000.m4s
#EXTINF:9.600000,
test_1080p_0001.m4s
#EXTINF:9.600000,
test_1080p_0002.m4s
#EXTINF:9.600000,
test_1080p_0003.m4s
#EXTINF:11.200000,
test_1080p_0004.m4s
#EXTINF:8.833333,
test_1080p_0005.m4s
#EXT-X-ENDLIST
```
I play the stream using [hls.js](https://github.com/video-dev/hls.js/) and works fine.

**Comment by ryancwalsh** [comment]
Thank you so much for working on this with me! :-)

```
ffmpeg -version
ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
```

**list_1080p.m3u8**
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://mysite.com/hls.key",IV=0xc9531244b6420e3781ebe87dd8e467d6
#EXT-X-MAP:URI="list_init.mp4"
#EXTINF:1.600000,
list_1080p_0000.m4s
#EXTINF:8.000000,
list_1080p_0001.m4s
#EXTINF:3.800000,
list_1080p_0002.m4s
#EXT-X-ENDLIST
```

```
ls storage/app/public/media/000000000/000000001/
list_1080p_0000.m4s  list_1080p_0001.m4s  list_1080p_0002.m4s  list_1080p.m3u8  list.m3u8
ls list_init.mp4
list_init.mp4
```

You can see that `list_init.mp4` is at the root directory instead of inside `storage/app/public/media/000000000/000000001/` with the other output files.

And I had been calling `->setHlsKeyInfoFile` instead of `->encryption($save_to, $url)` because of the way I'm handling my encryption.

But even when I switch to using the `->encryption($save_to, $url)` approach, `list_init.mp4` is at the root directory. 

I will try upgrading ffmpeg.

https://www.ffmpeg.org/download.html links to https://launchpad.net/ubuntu/+source/ffmpeg which was difficult to understand, but I think 4.1 is the current stable release.

https://askubuntu.com/a/727002/ did not seem to work. 

Then I found:
http://ubuntuhandbook.org/index.php/2018/10/install-ffmpeg-4-0-2-ubuntu-18-0416-04/
```
sudo add-apt-repository ppa:jonathonf/ffmpeg-4
sudo apt-get update
sudo apt-get install ffmpeg

ffmpeg -version
ffmpeg version 4.2.2-0york0~18.04 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
```

So now I'm using 4.2.2.

But damn, then I get this error when I try to use your library:

```
[hls @ 0x563f97298000] Encrypted fmp4 not yet supported
```

I wonder if I was better off with 3.4.6-0ubuntu0.18.04.1.

How can I install _your_ exact version of ffmpeg?

**Comment by ryancwalsh** [comment]
And now I'm noticing that with 4.2.2 the list_init.mp4 got created in the right place (but encoding failed and threw that "Encrypted fmp4 not yet supported" error). 

So maybe the problem is just a bug / quirk with ffmpeg, depending on the version.

I just need to find a version that supports encrypted fmp4 _and_ places the init.mp4 in the correct folder.

**Comment by aminyazdanpanah** [comment]
Actually I have the same issue. I get this error.
```bash
Encrypted fmp4 not yet supported
Could not write header for output file #0 (incorrect codec parameters ?): Not yet implemented in FFmpeg, patches welcome
```

Unfortunately, I do know which version of FFmpeg places the init.mp4 in the correct folder and also supports encrypted fmp4.

Please see [FFmpeg Change Log](https://github.com/FFmpeg/FFmpeg/blob/master/Changelog) for more information about FFmpeg versions. I think it helps you to find a version you want to.

**Comment by ryancwalsh** [comment]
Ok, thanks. I'll keep poking around, trying to figure it out.
