### ISSUE TITLE
typo bug in getSegmentFilename

### ISSUE THREAD

**Issue by ryancwalsh** [aminyazdanpanah/PHP-FFmpeg-video-streaming#33]
https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/4bc7af1f154bb8fdf24bda3af406f27e6d639508/src/Filters/HLSFilter.php#L100

In `getSegmentFilename`, I think you meant `$ext = ($this->hls->getHlsSegmentType() === "fmp4") ? "m4s" : "ts";` instead of `$ext = ($this->hls->getHlsFmp4InitFilename() === "fmp4") ? "m4s" : "ts";`

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I just fixed the bug and now you can update the package.
``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```

**Comment by ryancwalsh** [comment]
Cool, thanks!
