### ISSUE TITLE
master playlist is consisting duplicate line of max representation  

### ISSUE THREAD

**Issue by uttamsingh** [aminyazdanpanah/PHP-FFmpeg-video-streaming#34]
**Describe the bug**

Below is the sample laster playlist that I have generated 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=344064,RESOLUTION=426x240,NAME="240"
input_240p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=431104,RESOLUTION=640x360,NAME="360"
input_360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=574464,RESOLUTION=1280x720,NAME="720"
input_720p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=862208,RESOLUTION=1280x720,NAME="720"
input_720p.m3u8

this is resulting in more data download from cloud server 

**To Reproduce**

I am adding below to video object 
            $video = $this->FFMpeg->open('input.mp4');
            $video->HLS()
                ->autoGenerateRepresentations([240, 360, 720])
                ->encryption($save_to, $url, $key_info_path)
                ->setAdditionalParams(['-hls_flags', 'periodic_rekey'])
                ->setFormat($format)
                ->setHlsTime(5)
                ->X264()
                ->setHlsAllowCache(false)
                ->setTsSubDirectory('ts_files')
                ->save(null, $to_aws_cloud);

**Expected behavior**

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=344064,RESOLUTION=426x240,NAME="240"
input_240p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=431104,RESOLUTION=640x360,NAME="360"
input_360p.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=574464,RESOLUTION=1280x720,NAME="720"
input_720p.m3u8

also want way to define default representation in case of auto

**Screenshots**

**Desktop/Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. Ubuntu 18]
 - FFmpeg vesion [e.g. 4.1]
FFmpeg vesion 4

**Additional context**

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I just fixed the bug and now you can update the package.
``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
