### ISSUE TITLE
width not divisible by 2

### ISSUE THREAD

**Issue by ryancwalsh** [aminyazdanpanah/PHP-FFmpeg-video-streaming#35]
**Describe the bug**
`#0:0 (h264 (native) -> h264 (libx264)) Press [q] to stop, [?] for help [libx264 @ 0x557aed4d1d20] width not divisible by 2 (577x324) Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height Conversion failed!`

**To Reproduce**
1. I used `->HLS()` and `->autoGenerateRepresentations([])` on a video that had a width or height that wasn't an even number (in my case, 577x324).

**Expected behavior**
Properly encode video.

**Desktop/Server (please complete the following information):**
 - ffmpeg version 3.4.6-0ubuntu0.18.04.1

**Additional context**
I fixed the problem with the following code, which feels a little bit weird. Maybe you will come up with a better solution. Also note that I fixed a [typo in the phpdoc](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/v1.2.0/src/AutoReps.php#L159): 

    /**
     * @param $k_bitrate
     * @param $width
     * @param $height
     * @return Representation
     * @throws InvalidArgumentException
     */
    private function addRep($k_bitrate, $width, $height): Representation {
        $evenWidth = $this->roundUpToNextEvenNumber($width);
        $evenHeight = $this->roundUpToNextEvenNumber($height);
        return (new Representation)->setKiloBitrate($k_bitrate)->setResize($evenWidth, $evenHeight);
    }

    protected function roundUpToNextEvenNumber(float $input): int {//https://stackoverflow.com/a/34363542/
        $output = ceil($input); // Round up decimals to an integer
        if ($output % 2 == 1) {
            $output++; // If odd, add one
        }
        return $output;
    }

https://www.google.com/search?q=ffmpeg+%22width+not+divisible+by+2%22 shows lots of people with this problem, but I didn't like any of the solutions I saw.

**Comment by aminyazdanpanah** [comment]
Thank you so much for taking the time and effort in finding bugs(`typo in the phpdoc` and this one). I am not able to spend time on this project at the moment but I will try to find a solution in the next release.

**Comment by aminyazdanpanah** [comment]
I just fixed the bug and now you can update the package.

``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```

**Comment by ryancwalsh** [comment]
@aminyazdanpanah Thanks!
