### ISSUE TITLE
PHP Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command

### ISSUE THREAD

**Issue by PHPism** [aminyazdanpanah/PHP-FFmpeg-video-streaming#37]
**Describe the bug**
I get this error when I'm trying to convert mp4 video to encrypted hls video. This happens only with one video and not all of them.

`PHP Fatal error:  Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/videos_source/video_filename.mp4' '-c:v' 'libx264' '-s:v' '426x240' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '1' '-b:v' '367k' '-maxrate' '440k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'playlist_init.mp4' '-hls_segment_filename' '/videos_dist/video_filename.mp4/playlist_240p_%04d.ts' '-hls_key_info_file' '/tmp/php_ffmpeg_video_streaming/streamc7Prme' '-strict' '-2' '/videos_dist/video_filename.mp4/playlist_240p.m3u8' '-c:v' 'libx264' '-s:v' '853x480' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '1' '-b:v' '551k' '-maxrate' '661k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'playl in vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Stream.php on line 126`

**To Reproduce**
Conversion Code:
`$ffmpeg_config = [
	'timeout' => 0, // The timeout for the underlying process
];
$ffmpeg = FFMpeg::create($ffmpeg_config);
$video = $ffmpeg->open($video_source_path);
$video->HLS()->X264()->encryption($enc_key_save_to, $enc_key_url)->autoGenerateRepresentations([1080, 480, 240])->save($video_save_path.'/playlist.m3u8');`

**Desktop/Server (please complete the following information):**
 - OS: Server
 - Version: CentOS 7.7 with cPanel.
 - FFmpeg vesion: ffmpeg version N-52056-ge5d25d1147-static

**Additional context**
And when I run the command directly from terminal it works fine.
`/usr/local/bin/ffmpeg -y -i /videos_source/video_filename.mp4 -c:v libx264 -s:v 426x240 -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_list_size 0 -hls_time 10 -hls_allow_cache 1 -b:v 367k -maxrate 440k -hls_segment_type mpegts -hls_fmp4_init_filename playlist_init.mp4 -hls_segment_filename /videos_dist/video_filename.mp4/playlist_240p_%04d.ts -hls_key_info_file /tmp/php_ffmpeg_video_streaming/streamc7Prme -strict -2 /videos_dist/video_filename.mp4/playlist_240p.m3u8 -c:v libx264 -s:v 853x480 -crf 20 -sc_threshold 0 -g 48 -keyint_min 48 -hls_list_size 0 -hls_time 10 -hls_allow_cache 1 -b:v 551k -maxrate 661k -hls_segment_type mpegts -hls_fmp4_init_filename playl `

**Comment by aminyazdanpanah** [comment]
It seems like the error message is truncated. Please provide the full version of the error.
If that's the whole error message, then I think it is because of the `log_errors_max_len` in your `php.ini` file. 
You can set the value of this option to 0 to see the full error message or you can set it during the script's execution. Like this:
``` php
ini_set('log_errors_max_len', 0);

$ffmpeg_config = [ 'timeout' => 0 ]; 
$ffmpeg = FFMpeg::create($ffmpeg_config); 

$video = $ffmpeg->open($video_source_path); 

$video->HLS()
    ->X264()
    ->encryption($enc_key_save_to, $enc_key_url)
    ->autoGenerateRepresentations([1080, 480, 240])
    ->save($video_save_path . '/playlist.m3u8');
```

The better way is to pass a `Psr\Logger\LoggerInterface` object to send your logs to a file.
For example, you can use [Monolog - Logging](https://github.com/Seldaek/monolog) to send all your error and info messages to a file(i.g. `/var/log/ffmpeg-streaming.log`).

``` php
use Monolog\Handler\StreamHandler;
use Monolog\Logger;

$logger = new Logger('FFmpeg_Streaming');
$logger ->pushHandler(new StreamHandler('/var/log/ffmpeg-streaming.log')); // path to log file

$ffmpeg_config = [ 'timeout' => 0 ]; 
$ffmpeg = FFMpeg::create($ffmpeg_config, $logger); 

$video = $ffmpeg->open($video_source_path); 

$video->HLS()
    ->X264()
    ->encryption($enc_key_save_to, $enc_key_url)
    ->autoGenerateRepresentations([1080, 480, 240])
    ->save($video_save_path . '/playlist.m3u8');
```

After you get the full error message, please post it here to help you.

**Comment by PHPism** [comment]
Thank you very much for the info.
I have updated error reporting length and included Monolog and The error changed:
`FFmpeg_Streaming.ERROR: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/videos_source/video_filename.mp4' '-c:v' 'libx264' '-s:v' '426x240' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '1' '-b:v' '367k' '-maxrate' '440k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'playlist_init.mp4' '-hls_segment_filename' '/videos_dist/video_filename.mp4/playlist_240p_%04d.ts' '-hls_key_info_file' '/tmp/php_ffmpeg_video_streaming/streamyR4rES' '-strict' '-2' '/videos_dist/video_filename.mp4/playlist_240p.m3u8' '-c:v' 'libx264' '-s:v' '853x480' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '1' '-b:v' '551k' '-maxrate' '661k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'playlist_init.mp4' '-hls_segment_filename' '/videos_dist/video_filename.mp4/playlist_480p_%04d.ts' '-hls_key_info_file' '/tmp/php_ffmpeg_video_streaming/streamyR4rES' '-strict' '-2' '/videos_dist/video_filename.mp4/playlist_480p.m3u8': ffmpeg version N-52056-ge5d25d1147-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers   built with gcc 8 (Debian 8.3.0-6)   configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libfribidi --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg   libavutil      56. 42.101 / 56. 42.101   libavcodec     58. 76.100 / 58. 76.100   libavformat    58. 42.100 / 58. 42.100   libavdevice    58.  9.103 / 58.  9.103   libavfilter     7. 77.100 /  7. 77.100   libswscale      5.  6.101 /  5.  6.101   libswresample   3.  6.100 /  3.  6.100   libpostproc    55.  6.100 / 55.  6.100 [mov,mp4,m4a,3gp,3g2,mj2 @ 0xbbd0d80] st: 1 edit list: 1 Missing key frame while searching for timestamp: 0 [mov,mp4,m4a,3gp,3g2,mj2 @ 0xbbd0d80] st: 1 edit list 1 Cannot find an index entry before timestamp: 0. Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/videos_source/video_filename.mp4':   Metadata:     major_brand     : isom     minor_version   : 512     compatible_brands: isomiso2avc1mp41     creation_time   : 2014-02-23T11:48:27.000000Z   Duration: 00:04:02.07, start: 0.000000, bitrate: 693 kb/s     Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1280:1281 DAR 16:9], 564 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)     Metadata:       creation_time   : 2014-02-23T11:48:27.000000Z       handler_name    : VideoHandler     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)     Metadata:       creation_time   : 2014-02-23T11:47:42.000000Z       handler_name    : SoundHandler Stream mapping:   Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))   Stream #0:1 -> #0:1 (aac (native) -> aac (native))   Stream #0:0 -> #1:0 (h264 (native) -> h264 (libx264))   Stream #0:1 -> #1:1 (aac (native) -> aac (native)) Press [q] to stop, [?] for help [libx264 @ 0xbbfabc0] VBV maxrate specified, but no bufsize, ignored [libx264 @ 0xbbfabc0] using SAR=640/639 [libx264 @ 0xbbfabc0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512 [libx264 @ 0xbbfabc0] profile High, level 2.1, 4:2:0, 8-bit [libx264 @ 0xbbfabc0] 264 - core 159 r2991 1771b55 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=48 keyint_min=25 scenecut=0 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=20.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00 [libx264 @ 0xbbf2140] width not divisible by 2 (853x480) Error initializing output stream 1:0 -- Error while opening encoder for output stream #1:0 - maybe incorrect parameters such as bit_rate, rate, width or height Conversion failed!  [] []
`
I ran the command in terminal and the error was:
[libx264 @ 0xbf7b140] width not divisible by 2 (853x480)
Error initializing output stream 1:0 -- Error while opening encoder for output stream #1:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!

**Comment by PHPism** [comment]
I managed to work it around by checking dimensions before applying conversion and resize the video to another dimensions with even width and height. I tried padding as well, but for some reasons, ffmpeg didn't recognize the new width. I'm sharing its code anyway!

```
require '/vendor/autoload.php';
use Monolog\Handler\StreamHandler;
use Monolog\Logger;
use Streaming\FFMpeg\Exception\ExceptionInterface;
use Streaming\FFMpeg;
use FFMpeg\FFProbe;
use FFMpeg\Coordinate\Dimension;
use FFMpeg\Format\Video\X264;

$logger = new Logger('FFmpeg_Streaming');		
$logger ->pushHandler(new StreamHandler('ffmpeg-streaming.log', \Monolog\Logger::ERROR));  // Logging Error Level Only
$ffmpeg_config = [
	'timeout' => 0, // The timeout for the underlying process
];
$ffmpeg = FFMpeg::create($ffmpeg_config, $logger); 
$video = $ffmpeg->open($video_source_path);

$ffprobe = FFProbe::create();
$video_ffprobe = $ffprobe->streams($video_source_path)->videos()->first(); 
$video_dimensions = $video_ffprobe->getDimensions(); 
$video_width = $video_dimensions->getWidth();
$video_height = $video_dimensions->getHeight();
if($video_width % 2 != 0 || $video_height % 2 != 0) // checking for odd values.
{
	$video_bitRate = $video_ffprobe->get('bit_rate') / 1024; // Getting original file bitrate
	$video_temp_path = $video_source_path.".tmp.mp4"; // Creating temp resized file in the same directory with .tmp extension then adding .mp4 to allow ffmpeg detect output format.
	$fix_mode = "resize"; // I had to set it for resize since padding not working but I'm sharing the code may be someone find fix.
	if($fix_mode == "padding")
	{
		if($video_width % 2 != 0)
		{
			$video_width = (ceil($video_width/2)*2)+2;
		}
		if($video_height % 2 != 0)
		{
			$video_height = (ceil($video_height/2)*2)+2;
		}
		$video->filters()->pad(new Dimension($video_width, $video_height));
	}
	elseif($fix_mode == "resize")
	{
		if($video_width % 2 != 0)
		{
			$video_width = (floor($video_width/2)*2)-2;
		}
		if($video_height % 2 != 0)
		{
			$video_height = (floor($video_height/2)*2)-2;
		}
		$video->filters()->resize(new Dimension($video_width, $video_height), 'inset')->synchronize();
	}
	$video_format = new X264('aac', 'libx264'); // I'm using aac since it's the available audio encoder in my server.
	$video_format->setKiloBitrate($video_bitRate); // Using original bitrate to save space.
	$video->save($video_format, $video_temp_path);
	
	$ffmpeg = FFMpeg::create($ffmpeg_config, $logger); 
	$video = $ffmpeg->open($video_temp_path); // Re-Open resized Video and continue.
}
$video->HLS()->X264()->encryption($enc_key_save_to, $enc_key_url)->autoGenerateRepresentations([1080, 480, 240])->save($video_save_path.'/playlist.m3u8');
if(isset($video_temp_path))
{
	unlink($video_temp_path); // Deleting resized temp video from server.
}
```

**Comment by aminyazdanpanah** [comment]
Actually, the problem is the same as #35. I will resolve it so soon and will let you know when I fix it.

**Comment by aminyazdanpanah** [comment]
I just fixed the bug and now you can update the package.

``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
