### ISSUE TITLE
Everything seems to be broken after this update 

### ISSUE THREAD

**Issue by uttamsingh** [aminyazdanpanah/PHP-FFmpeg-video-streaming#39]
**Describe the bug**
Everything seems to be broken after this update. Nothing working as earlier 

**To Reproduce**
1. Go to '/../...'
2. On Line '...'
3. The code '....'

**Expected behavior**

**Screenshots**

**Desktop/Server (please complete the following information):**
 - OS: [e.g. Linux]
 - Version [e.g. Ubuntu 18]
 - FFmpeg vesion [e.g. 4.1]

**Additional context**

**Comment by aminyazdanpanah** [comment]
Please provide more details about the error you get. What exactly is the error?

As of version v1.2, some function names, and class names have been changed. Please take a look at the **[documentation](https://video.aminyazdanpanah.com/)** to find out more about these changes.

If you want to use the previous version of this package, you can easily change the package dependency version to the previous one in your `composer.json`. 

``` json
{
    "..."
    "require": {
        "..."
        "aminyazdanpanah/php-ffmpeg-video-streaming": "^1.1",
        "..."
    },
    "..."
}
```
After changing, you should update the composer
``` bash
composer update
```

**Comment by uttamsingh** [comment]
@aminyazdanpanah I have done that .. I am not getting error however it is now not generating representations. Infact the setSegSubDirectory directory also not working .. earlier ts_folder was working  but the new method is not working


                $video->hls()
                    ->x264()
                    ->autoGenerateRepresentations([720, 360])
//                    ->fragmentedMP4()
//                    ->encryption($save_to, $url)
//                    ->autoGenerateRepresentations(json_decode($streamRequest->resolutions, true))
//                    ->setFormat($format)
//                    ->setSegSubDirectory(self::$ts_folders)
//                    ->setHlsAllowCache(false)
                    ->save(null , [$to]);

Please let me know if I am not using correct way

**Comment by uttamsingh** [comment]
the output is like below 
Transferring /var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/5e8bde68a6b7e/input_720p2.ts 
Transferring /var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/5e8bde68a6b7e/input_720p1.ts 
Transferring /var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/5e8bde68a6b7e/input_720p0.ts 
Transferring /var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/5e8bde68a6b7e/input.m3u8

**Comment by uttamsingh** [comment]
number 1 ,2, 3 postfix is without any underscore or something

**Comment by uttamsingh** [comment]
hey @aminyazdanpanah I have build a streaming platform that is now stuck as I have updated can't proceed any change is not working. let me know if any other info you need to fix .. it is only generation 720p file not taking sub directory

**Comment by uttamsingh** [comment]
apparently it working when         $config = [
            'ffmpeg.binaries'  => env('FFMPEG_PATH', '/usr/bin/ffmpeg'),
            'ffprobe.binaries' => env('FFPROBE_PATH', '/usr/bin/ffprobe'),
            'timeout'          => 3600,
            'ffmpeg.threads'   => 12,
        ];
is removed form config 
but encryption is  not working yet with rotation

**Comment by uttamsingh** [comment]
[2020-04-07 05:43:26] local.ERROR: Error while encoding req=42 : Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/local/bin/ffmpeg' '-y' '-i' '/Users/uttamsingh/workspaces/php/stream/input/input.mp4' '-c:v' 'libx264' '-s:v' '426x240' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '0' '-b:v' '421k' '-maxrate' '505k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'ts_files/hls-stream_init.mp4' '-hls_segment_filename' 'videos/ts_files/hls-stream_240p_%04d.ts' '-hls_base_url' 'ts_files/' '-hls_flags' 'periodic_rekey' '-hls_key_info_file' '/private/var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/streamZDuzJI' '-0' '-hls_flags' '-1' 'periodic_rekey' '-strict' '-2' 'videos/hls-stream_240p.m3u8' '-c:v' 'libx264' '-s:v' '640x360' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '0' '-b:v' '561k' '-maxrate' '673k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'ts_files/hls-stream_init.mp4' '-hls_segment_filename' 'videos/ts_files/hls-stream_360p_%04d.ts' '-hls_base_url' 'ts_files/' '-hls_flags' 'periodic_rekey' '-hls_key_info_file' '/private/var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/streamZDuzJI' '-0' '-hls_flags' '-1' 'periodic_rekey' '-strict' '-2' 'videos/hls-stream_360p.m3u8' '-c:v' 'libx264' '-s:v' '1280x720' '-crf' '20' '-sc_threshold' '0' '-g' '48' '-keyint_min' '48' '-hls_list_size' '0' '-hls_time' '10' '-hls_allow_cache' '0' '-b:v' '842k' '-maxrate' '1010k' '-hls_segment_type' 'mpegts' '-hls_fmp4_init_filename' 'ts_files/hls-stream_init.mp4' '-hls_segment_filename' 'videos/ts_files/hls-stream_720p_%04d.ts' '-hls_base_url' 'ts_files/' '-hls_flags' 'periodic_rekey' '-hls_key_info_file' '/private/var/folders/66/m2qcmp0166v0r2vqq8v7k10c0000gn/T/php_ffmpeg_video_streaming/streamZDuzJI' '-0' '-hls_flags' '-1' 'periodic_rekey' '-strict' '-2' 'videos/hls-stream_720p.m3u8':

Error Output:

 ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Unrecognized option '0'.
Error splitting the argument list: Option not found

**Comment by aminyazdanpanah** [comment]
I have just tested [this command](#issuecomment-610120119) and you are right. If you set the `ffmpeg.threads` value in the config array, it won't work properly. I will resolve this bug.

Try to unset this value and run the code again. I created the HLS content using the following code and I played the stream using [hls.js](https://github.com/video-dev/hls.js/). But you should know, in the new version of FFmpeg, It does not support Encrypted fmp4(see #31).

``` php
$ffmpeg = Streaming\FFMpeg::create();

$video = $ffmpeg->open("/var/media/test.mp4");

$video->hls()
    ->fragmentedMP4()
//    ->encryption($save_to, $url, 10) // Uncommented if your FFmpeg version is compatible with fmp4 encryption
    ->setSegSubDirectory("segments")
    ->setHlsAllowCache(false)
    ->x264()
    ->autoGenerateRepresentations([360, 240])
    ->save(null , [$s3]);
```

https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/issues/39#issuecomment-610187168 : To use encryption in the rotation key format, you just need to pass an integer as a "key rotation period" to the `encryption` method.

``` php
$ffmpeg = Streaming\FFMpeg::create();

$video = $ffmpeg->open("/var/media/test.mp4");

$save_to = '/home/public_html/hls-keys/key';
$url = 'hls-keys/key';

$video->hls()
    ->encryption($save_to, $url, 10)
    ->x264()
    ->autoGenerateRepresentations()
    ->save('/var/media/hls-stream.m3u8'); 
```
 If you set this value to 1, each segment file will be encrypted with a new encryption key.

**Comment by uttamsingh** [comment]
when you plan to release this bug fix??

**Comment by uttamsingh** [comment]
I just ran job once again and could just one encryption file got generated 
$save_to = 'keys/' . "mypathsh". '/key';
$url = 'key'; [I kept it 'key' only to upload the same to the server url]
 
$r_240p  = (new Representation)->setKiloBitrate(150)->setResize(426, 240);
                $r_360p  = (new Representation)->setKiloBitrate(276)->setResize(640, 360);
                $r_720p  = (new Representation)->setKiloBitrate(2048)->setResize(1280, 720);

                $video->hls()
                    ->encryption($save_to, $url, 10)
                    ->x264()
                    ->setFormat($format)
                    ->setSegSubDirectory(self::$ts_folders)
                    ->addRepresentations([$r_240p, $r_360p, $r_720p])
                    ->setHlsAllowCache(false)
                    ->save('output/playlist.m3u8');

**Comment by aminyazdanpanah** [comment]
I just fixed the bug and now you can update the package.

``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```

https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/issues/39#issuecomment-610622405: Set the value of the key rotation period to 1 and try it again.
