### ISSUE TITLE
FFMpeg::create(array('timeout'=>0)) in mac generating wrong representations

### ISSUE THREAD

**Issue by uttamsingh** [aminyazdanpanah/PHP-FFmpeg-video-streaming#40]
**Describe the bug**

my ffmpeg with config 
FFMpeg::create(array('timeout'=>0)) in mac

--------
$video = $this->FFMpeg->open('stream/input/input.mp4');

                $video->hls()
                    ->x264()
                    ->encryption($save_to, $url)
                    ->setFormat($format)
                    ->setSegSubDirectory(self::$ts_folders)
                    ->autoGenerateRepresentations(json_decode($streamRequest->resolutions, true))
                    ->setHlsAllowCache(false)
                    ->save(null , [$to]);

json_decode($streamRequest->resolutions, true) = [720, 360, 240] 

resulting 
in input.m3u8
input_240p.m3u8
input_360p.m3u8
**input_540.m3u8** which is wrong 

If i don't use array('timeout'=>0) in ffmpeg object process times out after 5 mins

**To Reproduce**
1. Go to '/../...'
2. On Line '...'
3. The code '....'

**Expected behavior**
Please let me know how can give timeout to hls process and 540 files are generated instead of 720

**Screenshots**

**Desktop/Server (please complete the following information):**
 - OS: MAC
 - Version [10.15.3]
 - FFmpeg vesion [e.g. 4.1]

**Additional context**

**Comment by aminyazdanpanah** [comment]
I do not have a mac, but I do not really think that the problem is related to the `timeout` value in the config array.
it seems like the height of your original video is 540 and when you are using  `autoGenerateRepresentations` to create representations, it filters the value(original height) from an array you have passed.

If you want to set representations explicitly, you can use `addRepresentations` method.

``` php
$ffmpeg = Streaming\FFMpeg::create();

$video = $ffmpeg->open("/var/media/video.mp4");

$r_360p  = (new Representation)->setKiloBitrate(276)->setResize(640, 360);
$r_480p  = (new Representation)->setKiloBitrate(750)->setResize(854, 480);
$r_720p  = (new Representation)->setKiloBitrate(2048)->setResize(1280, 720);

$video->hls()
    ->x264()
    ->addRepresentations([$r_360p, $r_480p, $r_720p])
    ->save('/var/www/hls.m3u8');
```
