### ISSUE TITLE
Autogenerate representation for .mp4 file

### ISSUE THREAD

**Issue by rohitjalmi90** [aminyazdanpanah/PHP-FFmpeg-video-streaming#41]
Hello Guys,
I am using your library to create HLS files. It works great. I want to create .mp4 to multiple bitrates using this same library. Is it possible? Can I do something like 

$video->hls()
                    ->encryption($save_to, $url)
                    ->x264()
                    ->setFormat($format)
                    ->addRepresentations($rep)
                    ->autoGenerateRepresentations([r_720p,r_240p])
                    ->save(null , $destinationURL);

For mp4 source file and output as mp4 file itself in 720 and 240. I know I can use ffm-peg but from my understanding, I have to generate the individual file for each representation.

Regards,

**Comment by aminyazdanpanah** [comment]
"MP4 output format" is not in the scope of this project. You should use [PHP-FFMpeg](https://github.com/PHP-FFMpeg/PHP-FFMpeg) for this use case. 

``` php
use FFMpeg\Coordinate\Dimension;
use FFMpeg\Filters\Video\ResizeFilter;
use FFMpeg\Format\Video\X264;

$ffmpeg = FFMpeg\FFMpeg::create();

$video = $ffmpeg->open('/var/media/video_1080p.mp4');

$video
    ->addFilter(new ResizeFilter(new Dimension(426, 240)))
    ->save((new X264)->setKiloBitrate(150), '/var/media/video_240p.mp4');

$video
    ->addFilter(new ResizeFilter(new Dimension(1280, 720)))
    ->save((new X264)->setKiloBitrate(2048), '/var/media/video_720p.mp4');
```

You can also use [AutoReps](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/d136fe3150b8eca219a9090d1e506f8a8e88c0d7/src/AutoReps.php#L21) class to generate the `Representation` objects as an iterator. After generating representations, you can encode MP4 format files into multiple bitrates.
