### ISSUE TITLE
Encoded Files are not playable

### ISSUE THREAD

**Issue by itsrehanijaz** [aminyazdanpanah/PHP-FFmpeg-video-streaming#45]
**Describe the bug**
Hi, I'm having trouble with multi quality encoding. System is producing playlist and every file but files are not playable. If we encode each quality separately, then it plays fine. But then I need to recreate main Manifest file.

**To Reproduce**
`$360 = (new Representation)->setKiloBitrate(276)->setResize(640, 360);`
`$r_480p = (new Representation)->setKiloBitrate(750)->setResize(854, 480);`
`$video->HLS()`
`->setFormat($format)`
`->setHlsTime(8)`
`->setHlsAllowCache(false)`
`->fragmentedMP4()`
`->addRepresentations([$r_360, $r_480])`
`->save();`
Or
`$video->HLS()`
`->setFormat($format)`
`->setHlsTime(8)`
`->setHlsAllowCache(false)`
`->fragmentedMP4()`
`->autoGenerateRepresentations([360, 480])`
`->save();`

PS: This only happens if we choose `->fragmentedMP4()`

**Expected behavior**
It should have exported playable files which are possible only if we run it in loop and then encode each quality separately.

**Comment by aminyazdanpanah** [comment]
Ok, I will check this issue

**Comment by aminyazdanpanah** [comment]
Thank you for the report. I just fixed the bug and now you can update the package.

```bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
