### ISSUE TITLE
Update php-ffmpeg to 0.16

### ISSUE THREAD

**Issue by andrewkarpich** [aminyazdanpanah/PHP-FFmpeg-video-streaming#47]
**Is your feature request related to a problem? Please describe.**
php-ffmpeg/php-ffmpeg released 0.16 version. When installing a new version in project, composer has a version conflict with php-ffmpeg-video-streaming

**Describe the solution you'd like**
Is it possible update to version 0.16?

**Comment by aminyazdanpanah** [comment]
I just added `php-ffmpeg: 0.16` dependency to the `composer.json` and now you can update the package.

``` bash
composer update aminyazdanpanah/php-ffmpeg-video-streaming
```
