### ISSUE TITLE
autoGenerateRepresentations() Bug (with vertical videos?)

### ISSUE THREAD

**Issue by userlip** [aminyazdanpanah/PHP-FFmpeg-video-streaming#49]
**Describe the bug**

I am using the following code:

`      $video->dash()
            ->setFormat($format)
            ->generateHlsPlaylist()
            ->autoGenerateRepresentations([360, 480, 720, 1080])
            ->save(null, $to_s3);`

In the .m3u8 file there should be 4 streams of my video. yet if I use a 4K video using these settings the code will create also create the 2160p video stream.

You can test it with the following Video: https://fuego-files.s3.eu-central-1.amazonaws.com/public/16612219545e3d64db55f19/1587737965e3d64d711a36/video/video.mp4

**To Reproduce**
Use the code from above and the video from above.

**Expected behavior**
There should be no 2160p stream

**Desktop/Server (please complete the following information):**
ffmpeg version 4.2.2-1ubuntu1~18.04

**Comment by aminyazdanpanah** [comment]
When you use the `autoGenerateRepresentations` method to generate `Representation` objects, the result contains the original representation + calculated representations(it filters the value(original height) from an array you have passed).

If you want to set representations explicitly, you can use `addRepresentations` method(see #40)

If you want to use only 'calculated representations', try the following code:

``` php
$format = new Streaming\Format\X264();
$format->on('progress', function ($video, $format, $percentage){
    echo sprintf("\rTranscoding...(%s%%) [%s%s]", $percentage, str_repeat('#', $percentage), str_repeat('-', (100 - $percentage)));
});

$log = new Logger('FFmpeg_Streaming');
$log->pushHandler(new StreamHandler('ffmpeg-streaming.log')); // path to log file

$ffmpeg = Streaming\FFMpeg::create(['timeout' => 0, $log);

$video = $ffmpeg->open('var/media/video.mp4');

$reps = new Streaming\AutoReps($video, $format, [360, 480, 720, 1080]);

$video->dash()
    ->setFormat($format)
    ->generateHlsPlaylist()
    ->addRepresentations($reps->getCalculatedReps())
    ->save(null, $to_s3);
```
