### ISSUE TITLE
Can we use a nvidia nvenc format?

### ISSUE THREAD

**Issue by redconan** [aminyazdanpanah/PHP-FFmpeg-video-streaming#51]
I need to use a GPU accelered to make my project. 
Have a way to this?
GPU: RTX6000
Formats: h264_nvenc or hevc_nvenc

**Comment by aminyazdanpanah** [comment]
see #27 

**NOTE:** instead of `Streaming\Format\Video`, the class extends `Streaming\Format\StreamFormat`.
