### ISSUE TITLE
How to use autoGenerateRepresentations

### ISSUE THREAD

**Issue by byLogin** [aminyazdanpanah/PHP-FFmpeg-video-streaming#52]
How to use autoGenerateRepresentations to create regular mp4 videos, not hls

like that:
$video = $ffmpeg->open ('video.mp4');
$video->autoGenerateRepresentations ([144,240])->save ();
?

**Comment by aminyazdanpanah** [comment]
"MP4 output format" is not in the scope of this project. You should use PHP-FFMpeg for this use case. (see #41)

You can also use **[`AutoReps`](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/d136fe3150b8eca219a9090d1e506f8a8e88c0d7/src/AutoReps.php#L21) class** to auto-generate Representation Object and convert your video into different sizes(or bitrates).

``` php
$ffmpeg = Streaming\FFMpeg::create();

$video = $ffmpeg->open('path/to/video');

$format = new FFMpeg\Format\Video\X264();

$reps = new Streaming\AutoReps($video, $format, [144, 240]);

foreach ($reps as $rep){
    $video
        ->addFilter(new ResizeFilter($rep->getSize()))
        ->save($format->setKiloBitrate($rep->getKiloBitrate()), sprintf('/var/media/video_%sp.mp4', $rep->getHeight()));
}
```
