### ISSUE TITLE
I can't anti download from tool download

### ISSUE THREAD

**Issue by HP161** [aminyazdanpanah/PHP-FFmpeg-video-streaming#53]
I can't anti download from tool download.
my code here: 
  //A path you want to save a random key to your local machine
        $save_to = base_path() . '/lib/' . $randomString . '/key';
        //A URL (or a path) to access the key on your website
        $url = url('/') . '/lib/enc.key';
        // or $url = '/"PATH TO THE KEY DIRECTORY"/key';
        $format = new Streaming\Format\X264();
        $format->on('progress', function ($video, $format, $percentage) {
            echo sprintf("\rTranscoding...(%s%%) [%s%s]", $percentage, str_repeat('#', $percentage), str_repeat('-', (99 - $percentage)));
        });
        $video->hls()
            ->x264()
            ->setFormat($format)
            ->encryption($save_to, $url, 1)
            ->autoGenerateRepresentations([720, 360]) // You can limit the numbers of representatons
            ->save(base_path() . '/lib/' . $randomString . '/' . $randomString . '.m3u8');

please help, thanks!

**Comment by aminyazdanpanah** [comment]
As I mentioned in the documentation, the encryption is not a full **[DRM](https://en.wikipedia.org/wiki/Digital_rights_management)**. 

You can use DRM systems such as **[Apple's FairPlay](https://developer.apple.com/streaming/fps/)**, **[Microsoft's PlayReady](https://www.microsoft.com/playready/overview/)**, and **[Google's Widevine](https://www.widevine.com/)**. to securely exchange keys and protect playback on devices.

If you do not want to use any DRM system, I recommend protecting your key on your server.

Personally I use a **[CSRF token](https://portswigger.net/web-security/csrf/tokens)** to restrict access to the key(s) to any Download Manager software like IDM. 

You can also use [this technique](https://medium.com/@onetdev/custom-key-acquisition-for-encrypted-hls-in-videojs-59e495f78e52) by [József Koller](https://medium.com/@onetdev) on Medium.

**Comment by HP161** [comment]
thanks @aminyazdanpanah
