### ISSUE TITLE
Delete hls segments automatically from time to time and PID fetching 

### ISSUE THREAD

**Issue by DanielQuirogaDev** [aminyazdanpanah/PHP-FFmpeg-video-streaming#54]
I am working in a live stream solution and it is already working, there are two things that would be great: Cleaning automatically the hls segments so it doesnt clutter the server (Right now i am using a custom command) and i'd like to get the PID for each thread so i can control who stalls and who keeps on running so i can kill and relaunch the process. 

Another thing that would be really useful  is the ability to follow the execution status of the process but this i think i will contribute.

Will also add the nvenc settings for you.

**Comment by aminyazdanpanah** [comment]
You can use the ‘delete_segments’ flag. It allows you to remove segment files from the playlist are deleted after a period of time equal to the duration of the segment plus the duration of the playlist.

``` php
$ffmpeg = FFMpeg::create();

$video = $ffmpeg->open('/var/media/video.mp4');

$video->hls()
    ->setHlsListSize(5)
    ->setFlags([\Streaming\HLSFlag::DELETE_SEGMENTS]) 
    ->x264()
    ->addRepresentation($r_480p)
    ->save('/var/media/hls-stream.mpd');
```

See **[HLS Options](https://ffmpeg.org/ffmpeg-formats.html#hls-2)** for more information.

When you run a script, you can add the following code to get PHP's process ID and kill it:
```php
$pid = getmypid(); // get pid

posix_kill(intval($pid), 0)  // kill process
```
See [getmypid](https://www.php.net/manual/en/function.getmypid.php) and [posix_kill](https://www.php.net/manual/en/function.posix-kill.php) for more information.

See #51. #27 to figure out how to add a custom format like nvenc.

**Comment by DanielQuirogaDev** [comment]
$pid = getmypid(); // get pid

posix_kill(intval($pid), 0)  // kill process

I already check out getmypid, but if i am going to handle hls from php i need to get the ffmpeg process id so i can kill it.

Thanks for your detailed and really useful answer.

**Comment by aminyazdanpanah** [comment]
Currently, it is not possible to get the PID of the subprocess (FFmpeg process) using this project.
But when you kill a PHP process, it will kill the whole subprocess of it(including the FFmpeg process- it kills the tree thread).

Alternatively, you can use the [Symfony Process Component](https://github.com/symfony/process) to get the PID of the subprocess.

Also, see [proc_get_status](https://www.php.net/manual/en/function.proc-get-status.php).
