### ISSUE TITLE
CAN WE USE THIS ONE IN PRODUCTION 

### ISSUE THREAD

**Issue by ngcgolf11** [aminyazdanpanah/PHP-FFmpeg-video-streaming#56]
Hi Aminyazdanpanah,

Can we use this software in production environment and how it will get to know what is resolution  of input file it got this automatically or we have to do that manually.

we want a open source software which detect the input stream and transcode the video into dash format automatically and after transcoding it will check media is transcoded or not successfully

**Comment by aumkarthakur** [comment]
It works great for VOD solution we are using it in production environment for our clients. Converting mp4 to hls and storing it on DigitalOcean Spaces.

**Comment by ngcgolf11** [comment]
Hi Auumkar,
we want to transcode videos into dash and want to store on aws s3

**Comment by aumkarthakur** [comment]
Please read the documentation for uploading to cloud services like AWS s3 here:

[https://video.aminyazdanpanah.com/start/clouds?r=save](https://video.aminyazdanpanah.com/start/clouds?r=save)

The above documentation code is using hls conversion you can modify it to work with dash easily like this:

```
$config = [
    'version'     => 'latest',
    'region'      => 'us-west-1', // the region of your cloud server
    'credentials' => [
        'key'    => 'access-key-id', // the key to authorize you on the server
        'secret' => 'secret-access-key', // the secret to access to the cloud
    ]
];
$s3 = new Streaming\Clouds\S3($config);

$from_s3 = [
    'cloud' => $s3,
    'options' => [
        'Bucket' => 'bucket-name', // name of your bucket
        'Key' => '/videos/video.mp4' // your file name on the cloud
    ]
];

$to_s3 = [
    'cloud' => $s3,
    'options' => ['dest' => 's3://bucket-name'] // name of your bucket
];

$ffmpeg = Streaming\FFMpeg::create();

$video = $ffmpeg->openFromCloud($from_s3);
// you can also use open method to open a file from a local path
// $video = $ffmpeg->open('/var/media/video.mp4');

$video->dash()
    ->x264()
    ->autoGenerateRepresentations()
    ->save(null, $to_s3); // you can also pass a local path to save a copy of files to your server
```

Here is my code, I take file from my localserver and convert it to dash and upload it to AWS S3 and then print the folder which I have uploaded all files to:

```
<?php

require 'vendor/autoload.php';

use Streaming\Clouds\S3;
use Aws\S3\S3Client;


$config = [
        'version' => 'latest',
        'region'  => 'nyc3',
        'endpoint' => 'https://nyc3.digitaloceanspaces.com',
        'credentials' => [
                'key'    => 'access-key-id',
                'secret' => 'secret-access-key',
            ],
];
$s3 = new Streaming\Clouds\S3($config);
$s32 = new Aws\S3\S3Client($config);


$to_s3 = [
    'cloud' => $s3,
    'options' => ['dest' => 's3://bucket-name/new-folder']
];


$config = [
    'timeout'          => 0 // The timeout for the underlying process
];


$ffmpeg = Streaming\FFMpeg::create($config, null);
$video = $ffmpeg->open('/var/www/html/ffmpeg/1782829481.mp4');



$video = $video->dash()
   	->x264()
    ->autoGenerateRepresentations([480, 720])
    ->save(null, $to_s3);
    


echo '<pre>';
$objects = $s32->getIterator('ListObjects', ['Bucket' => 'bucket-name', 'delimiter'=>'/', 'Prefix' => 'new-folder']);
foreach ($objects as $object) {
    echo $object['Key'] . "\n";
}
echo '</pre>';



    
    ?>
```

**Comment by aminyazdanpanah** [comment]
This library is an open-source project and is under the MIT license. I cannot provide specific legal advice.  However, I can say in general that if a software is under a free software license like MIT, you can use it in your production software.

See **[License File](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming/blob/master/LICENSE)** for more information.
