### ISSUE TITLE
/var/tmp folder can get full if you're uploading larger file with many Representations

### ISSUE THREAD

**Issue by aumkarthakur** [aminyazdanpanah/PHP-FFmpeg-video-streaming#58]
**Describe the bug**
I had this problem and it took me a day to find out that /tmp folder size was only 1.5GB and hls output was like "5GB" so my code was failing again and again even when things like max_file_upload limits were infinite.

**Solution**
If you're facing similar problem please use following solution:

[https://askubuntu.com/questions/199565/not-enough-space-on-tmp](https://askubuntu.com/questions/199565/not-enough-space-on-tmp)

**Comment by aminyazdanpanah** [comment]
Thank you so much for the solution.
