### ISSUE TITLE
Does it work with audio-only files ?

### ISSUE THREAD

**Issue by digitimage** [aminyazdanpanah/PHP-FFmpeg-video-streaming#59]
Hi
Is there a way to convert audio-only file using HLS ?
I tried to do: $ffmpeg->open(input.mp3)->hls()->save(output.m3u8) but got an "Audio only accepts AudioFilterInterface filters" error 

From ffmpeg binary, the command line is : "ffmpeg -i input.mp3 -options -f hls output.m3u8"

Thanks
Cyril

**Comment by aumkarthakur** [comment]
Can you try using something like this ?

```
$video = $ffmpeg->open('/var/media/song.mp3');

$video = $video->hls()
        ->x264()
        -> autoGenerateRepresentations()
        ->save('/var/media/song-stream.m3u8');

```

i can't find anything about mp3 to hls conversion in doc, maybe you should wait for Amin to reply.
