### ISSUE TITLE
Allow Initial Parameters

### ISSUE THREAD

**Issue by syntaxevolution** [aminyazdanpanah/PHP-FFmpeg-video-streaming#61]
**Is your feature request related to a problem? Please describe.**
php-ffmpeg allows you to set initial parameters now and the latest prerelease is using this version of php-ffmpeg but doesn't allow setting of the initial parameters.

**Describe the solution you'd like**
Ability to call setInitialParameters just as in php-ffmpeg

**Describe alternatives you've considered**
No other method of setting initial parameters such as -presets veryfast at the moment.

**Additional context**
Please see https://github.com/PHP-FFMpeg/PHP-FFMpeg/pull/703

**Comment by aminyazdanpanah** [comment]
**Usage:**

```php
$format = new X264();
$format->setInitialParameters(['param1', 'param2', ...]);

$ffmpeg = Streaming\FFMpeg::create();

$video = $ffmpeg->open('/var/media/video.mp4');

$video->hls()
    ->setFormat($format)
    ->autoGenerateRepresentations([720, 480])
    ->save('/var/media/hls.m3u8');
```
