### ISSUE TITLE
Unable to upload to the gcp bucket directly

### ISSUE THREAD

**Issue by csrujan** [aminyazdanpanah/PHP-FFmpeg-video-streaming#65]
using the mentioned code for in the document unable to upload mpd files directly to the cloud

**Comment by aminyazdanpanah** [comment]
It seems like your question is related to the [python-ffmpeg-video-streaming](https://github.com/aminyazdanpanah/python-ffmpeg-video-streaming) (as your previous question was related to that) not this repository.
