### ISSUE TITLE
Unable to probe from mp4 link

### ISSUE THREAD

**Issue by sintexph** [aminyazdanpanah/PHP-FFmpeg-video-streaming#67]
I tried this code but I got an error saying unable to probe
```

       $upload=$episode->upload;
        $stream=new FTPStreamHelper($upload->file_path);
        $config = [
            'ffmpeg.binaries'  => 'F:/ffmpeg/bin/ffmpeg.exe',
            'ffprobe.binaries' => 'F:/ffmpeg/bin/ffprobe.exe',
        ];

        $log = new Logger('FFmpeg_Streaming');
        $log->pushHandler(new StreamHandler('F:\ffmpeg-streaming.log')); // path to log file
            
        $ffmpeg = \Streaming\FFMpeg::create($config, $log);

        $video = $ffmpeg->open("http://techslides.com/demos/sample-videos/small.mp4");

        $video->dash()
            ->x264() // Format of the video. Alternatives: hevc() and vp9()
            ->autoGenerateRepresentations() // Auto generate representations
            ->save(public_path('video-stream.mpd')); // It can be passed a path to the method or it can be null

```

![image](https://user-images.githubusercontent.com/47470967/88266510-e9d60480-cd01-11ea-8e7c-48767771cf25.png)

but when I try to do it manually in CMD, I think it seems fine

![image](https://user-images.githubusercontent.com/47470967/88266715-3cafbc00-cd02-11ea-8293-c4c7de8fe0db.png)

**Comment by aminyazdanpanah** [comment]
As can be seen in your image your local machine failed to resolve the hostname.

![88266510-e9d60480-cd01-11ea-8e7c-48767771cf25](https://user-images.githubusercontent.com/3193929/89107433-578ed880-d446-11ea-8476-2f7bc6f9bfe3.png)

Make sure the URL(http://techslides.com/demos/sample-videos/small.mp4) is correct and you are connected to the Internet.
