### ISSUE TITLE
Small typo in readme..

### ISSUE THREAD

**Issue by ffd8** [aminyazdanpanah/PHP-FFmpeg-video-streaming#68]
There's an extra `$` in [this snippet of the readme](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming#other-advanced-features):

$ffmpeg = Streaming\FFMpeg::create()
$video = ~**$**~$ffmpeg->openFromCloud($from_cloud, '/var/wwww/media/my/new/video.mp4');

**Comment by aminyazdanpanah** [comment]
Thanks for the report.
