### ISSUE TITLE
How to upload file into specific directory with specific inside google cloud?

### ISSUE THREAD

**Issue by Ulsah** [aminyazdanpanah/PHP-FFmpeg-video-streaming#70]
Hello there,

I'm using this library to convert videos for DASH streaming and store the files to my google cloud storage. It works fine except that the files are stored into my google storage's root directory with auto generated names. Please help me store the generated files into a specific directory with a name of of my choosing.

Thank you.

**Comment by aminyazdanpanah** [comment]
I have just added this feature and now you should update the package. After updating, see **[this example](https://video.aminyazdanpanah.com/start/clouds?r=save#google)** to learn how to upload files with a specific name.
