### ISSUE TITLE
Anyway to begin streaming while ffmpeg is still transcode video file?

### ISSUE THREAD

**Issue by MarlonEtiene** [aminyazdanpanah/PHP-FFmpeg-video-streaming#71]
Hello,
Sorry for no use any templates, because it is not a bug, just a question.
I really like to know, if have anyway to start play video while ffmpeg busy with transcode?

**Comment by aminyazdanpanah** [comment]
The manifest and initial segments are the first things that FFmpeg will create after you run the code. If these files are created, then you will be able to play it in a video player. But you should note, you cannot play entire the video until the process has been finished(only the first segments are playable).

For example, you can run a script to create HLS or DASH content and at the same time, play it in a video player.
