### ISSUE TITLE
FFproble issue

### ISSUE THREAD

**Issue by augustinejenin** [aminyazdanpanah/PHP-FFmpeg-video-streaming#77]
**Describe the bug**
I installed ffmpeg and used this library but when i use this $video = $ffmpeg->open('/var/media/video.mp4');
I got below error. please let me know what we have to do

Fatal error: Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffprobe failed to execute command '/usr/local/bin/ffprobe' '-help' '-loglevel' 'quiet': Error Output: /usr/local/bin/ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0) /usr/local/bin/ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0) /usr/local/bin/ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5) /usr/local/bin/ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5) /usr/local/bin/ffprobe: /opt/lampp/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5) /usr/local/bin/ffprobe: /opt/lampp/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/librubberband.so. in /opt/lampp/htdocs/test/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/FFMpeg.php on line 51

 - OS: [e.g. Linux]
 - FFmpeg vesion 3.4.8-0 ubuntu0.2

Please let me know how we can fix this issue?

**Comment by nikoz84** [comment]
maybe your ffprobe need a dependency, `/opt/lampp/lib/libstdc++.so.6: version CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)` that dependency is not installed

sudo apt-get install libstdc++6

[see this issue here ](https://github.com/microsoft/napajs/issues/93#issuecomment-338504478)

**Comment by aminyazdanpanah** [comment]
Open a new terminal and run the following command. You will see the error message and the dependencies that you should install them.
``` bash
/usr/local/bin/ffprobe -help -loglevel quiet'
```
