### ISSUE TITLE
Not divisible by zero

### ISSUE THREAD

**Issue by bekee** [aminyazdanpanah/PHP-FFmpeg-video-streaming#80]
I;m running on php7.3, sometimes this line of code works and most times it fails at point 

> $seconds_left = 100 * $diff_time / $percentage - $diff_time;

Please I need your assistance

$percentage_to_time_left = function ($percentage) use (&$start_time) {
    if($start_time === 0){
        $start_time = time();
        return "Calculating...";
    }

    $diff_time = time() - $start_time;
    $seconds_left = 100 * $diff_time / $percentage - $diff_time;

    return gmdate("H:i:s", $seconds_left);
};

**Comment by aminyazdanpanah** [comment]
Try this:
``` php
$percentage_to_time_left = function ($percentage) use (&$start_time) {
    if($start_time === 0){
          $start_time = time();
           return "Calculating...";
     }

     if ($percentage === 0){
           return "wait...";
     }

     $diff_time = time() - $start_time;
     $seconds_left = 100 * $diff_time / $percentage - $diff_time;

     return gmdate("H:i:s", $seconds_left);
};
```
