### ISSUE TITLE
Encrypted hls on iphone

### ISSUE THREAD

**Issue by shankar-bavan** [aminyazdanpanah/PHP-FFmpeg-video-streaming#81]
This is not Bug
I used this [technique ](https://onetdev.medium.com/custom-key-acquisition-for-encrypted-hls-in-videojs-59e495f78e52) to play encrypted hls file. It is work on android. but not work on iphone. 
Is there any solution ?

**Comment by aminyazdanpanah** [comment]
As the author mentioned, browsers without Media Source Extension might have difficulties working with this solution (like iOS Safari) and I have never worked with native HLS supporting browsers, so I do not have any solution, sorry!
