### ISSUE TITLE
Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command '/usr/bin/ffmpeg' '-y' '-i' '/var/www/myProject/releases/4/storage/app/public/

### ISSUE THREAD

**Issue by zykyan** [aminyazdanpanah/PHP-FFmpeg-video-streaming#86]
Error Output:

 ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/var/www/myProject/releases/4/storage/app/public/subtopics/3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5/subtopics-3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    creation_time   : 2020-03-27T19:30:36.000000Z
  Duration: 00:00:10.86, start: 0.000000, bitrate: 15823 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160, 15585 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 60k tbc (default)
    Metadata:
      creation_time   : 2020-03-27T19:30:36.000000Z
      handler_name    : L-SMASH Video Handler
      encoder         : AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 253 kb/s (default)
    Metadata:
      creation_time   : 2020-03-27T19:30:36.000000Z
      handler_name    : L-SMASH Audio Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
  Stream #0:0 -> #0:2 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:3 (aac (native) -> aac (native))
  Stream #0:0 -> #0:4 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:5 (aac (native) -> aac (native))
  Stream #0:0 -> #0:6 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:7 (aac (native) -> aac (native))
  Stream #0:0 -> #0:8 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:9 (aac (native) -> aac (native))
  Stream #0:0 -> #0:10 (h264 (native) -> h264 (libx264))
  Stream #0:1 -> #0:11 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[libx264 @ 0x5644ee866800] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5644ee866800] profile High, level 1.2
[libx264 @ 0x5644ee866800] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=95 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0x5644ee83ed00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5644ee83ed00] profile High, level 2.1
[libx264 @ 0x5644ee83ed00] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=150 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0x5644ee83a880] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5644ee83a880] profile High, level 3.0
[libx264 @ 0x5644ee83a880] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=276 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0x5644ee85e4c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5644ee85e4c0] profile High, level 3.1
[libx264 @ 0x5644ee85e4c0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=750 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0x5644ee8684c0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5644ee8684c0] profile High, level 3.1
[libx264 @ 0x5644ee8684c0] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=2048 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[libx264 @ 0x5644ee86c900] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5644ee86c900] profile High, level 4.0
[libx264 @ 0x5644ee86c900] 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=1 b_pyramid=0 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=abr mbtree=1 bitrate=4096 ratetol=1.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
frame=    5 fps=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 q=0.0 size=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    
[dash @ 0x5644ee865180] Opening '/var/www/myProject/releases/4/storage/app/public/subtopics/3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5/subtopics-3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5_init_0.m4s' for writing
Could not write header for output file #0 (incorrect codec parameters ?): Permission denied
Error initializing output stream 0:11 -- 
[libx264 @ 0x5644ee866800] final ratefactor: 36.37
[aac @ 0x5644ee83d800] Qavg: -nan
[aac @ 0x5644ee83d800] 1 frames left in the queue on closing
[libx264 @ 0x5644ee83ed00] final ratefactor: 36.90
[aac @ 0x5644ee85bb80] Qavg: -nan
[aac @ 0x5644ee85bb80] 1 frames left in the queue on closing
[libx264 @ 0x5644ee83a880] final ratefactor: 35.17
[aac @ 0x5644ee95e200] Qavg: -nan
[aac @ 0x5644ee95e200] 1 frames left in the queue on closing
[libx264 @ 0x5644ee85e4c0] final ratefactor: 28.96
[aac @ 0x5644ee860d80] Qavg: -nan
[aac @ 0x5644ee860d80] 1 frames left in the queue on closing
[libx264 @ 0x5644ee8684c0] final ratefactor: 23.72
[aac @ 0x5644ee86aec0] Qavg: -nan
[aac @ 0x5644ee86aec0] 1 frames left in the queue on closing
[libx264 @ 0x5644ee86c900] final ratefactor: 21.27
[aac @ 0x5644ee86f5c0] Qavg: -nan
Conversion failed!
 in /var/www/myProject/releases/1/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php:95
Stack trace:
#0 /var/www/myProject/releases/1/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/ProcessRunner.php(73): Alchemy\BinaryDriver\ProcessRunner->doExecutionFailure()
#1 /var/www/myProject/releases/1/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(207): Alchemy\BinaryDriver\ProcessRunner->run()
#2 /var/www/myProject/releases/1/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php(136): Alchemy\BinaryDriver\AbstractBinary->run()
#3 /var/www/myProject/releases/1/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Stream.php(128): Alchemy\BinaryDriver\AbstractBinary->command()
#4 /var/www/myProject/releases/1/vendor/aminyazdanpanah/php-ffmpeg-video-streaming/src/Stream.php(163): Streaming\Stream->run()
#5 /var/www/myProject/releases/1/app/Jobs/FormatVideo.php(64): Streaming\Stream->save()
#6 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\FormatVideo->handle()
#7 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#9 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#10 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#11 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call()
#12 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#13 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then()
#15 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow()
#16 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#17 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#18 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then()
#19 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#20 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#21 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#22 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process()
#23 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob()
#24 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#25 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#26 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#27 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#29 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#30 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call()
#31 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#32 /var/www/myProject/releases/1/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute()
#33 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#34 /var/www/myProject/releases/1/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#35 /var/www/myProject/releases/1/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#36 /var/www/myProject/releases/1/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#37 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#38 /var/www/myProject/releases/1/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#39 /var/www/myProject/releases/1/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#40 {main}

**Comment by aminyazdanpanah** [comment]
The error message:

```bash
[dash @ 0x5644ee865180] Opening '/var/www/myProject/releases/4/storage/app/public/subtopics/3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5/subtopics-3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5_init_0.m4s' for writing
Could not write header for output file #0 (incorrect codec parameters ?): Permission denied
```

Check permissions of the following directory:

```text
/var/www/myProject/releases/4/storage/app/public/subtopics/3801bfef-95b5-43a9-9c5b-dfc6cc01b8a5
```
