### ISSUE TITLE
Additional audio tracks

### ISSUE THREAD

**Issue by gpmaestro** [aminyazdanpanah/PHP-FFmpeg-video-streaming#87]
Hey, I need to add more audio tracks to the HLS streaming. Is there any solution to generate a separate m3u8 playlist for an AAC file and include it in the main playlist?

Thanks a lot!

**Comment by aminyazdanpanah** [comment]
You can create an additional m3u8 playlist for an AAC file using FFmpeg Library and you should also modify the master playlist(master.m3u8) to add audio m3u8 playlists.
