### ISSUE TITLE
Subtitles are not included in the master.m3u8 file

### ISSUE THREAD

**Issue by adis0308** [aminyazdanpanah/PHP-FFmpeg-video-streaming#88]
Subtitles from mkv videos with softsub are not automatically inserted into the master.m3u8 file even though they are also converted.

**Comment by aminyazdanpanah** [comment]
Embedded Subtitles are not supported in this library. You need to specify a 'VTT 'file path and pass it to the HLSSubtitle object.

See [the sample](https://github.com/aminyazdanpanah/PHP-FFmpeg-video-streaming#subtitles) for more information.
