### ISSUE TITLE
Converting video to hls with fragmentedMP4 failed

### ISSUE THREAD

**Issue by adis0308** [aminyazdanpanah/PHP-FFmpeg-video-streaming#90]
**PHP Fatal error:**  Uncaught Alchemy\BinaryDriver\Exception\ExecutionFailureException: ffmpeg failed to execute command "E:/laragon/www/gdplayer-hosting/tools/ffmpeg/win_64/bin/ffmpeg.exe" -y -i "E:\laragon\www\gdplayer-hosting\content-kbasdy324jkad-aasuyk1243km\uploads\176ea42d-3099-427c-9406-7b29497b8454\Kobayashi-san Chi no Maid Dragon 11 720p.mkv" -c:v libx264 -c:a aac -bf 1 -keyint_min 25 -g 250 -sc_threshold 40 -hls_list_size 0 -hls_time 10 -hls_allow_cache 1 -hls_segment_type fmp4 -hls_fmp4_init_filename master_360p_init.mp4 -hls_segment_filename "E:/laragon/www/gdplayer-hosting/content-kbasdy324jkad-aasuyk1243km/hls/176ea42d-3099-427c-9406-7b29497b8454/**master_360p_"^%"04d.m4s"** -s:v 640x360 -b:v 685k -hls_key_info_file "C:\Users\Adis\AppData\Local\Temp\php_ffmpeg_video_streaming/pfvs.file_20114843306034b4d2b287c" -strict -2 "E:/laragon/www/gdplayer-hosting/content-kbasdy324jkad-aasuyk1243km/hls/176ea42d-3099-427c-9406-7b29497b8454/master_360p.m3u8" -c:v libx264 -c:a aac -bf 1 -keyint_min 25 -g 250 -sc_threshold 40 -hls_li in E:\laragon\www\gdplayer-hosting\vendor\alchemy\binary-driver\src\Alchemy\BinaryDriver\ProcessRunner.php on line 95

**Comment by aminyazdanpanah** [comment]
The error message has been truncated see #37 to figure out how to see the complete error message.
