### ISSUE TITLE
How to insert multiple language audios in DASH? 

### ISSUE THREAD

**Issue by rotneto** [aminyazdanpanah/PHP-FFmpeg-video-streaming#91]
I read several examples here from the discussion and found this #21 which is perfect, but I would like to know if besides the subtitles of languages it is also possible to add more than one audio with different language?

With the software BENTO4 or MP4Box it is possible to add the audio and mark the MPD file in the AUDIO tag with LANG attribute.
Is this possible with ffmpeg?

**Comment by aminyazdanpanah** [comment]
I do think FFmpeg supports this feature(You can find out FFmpeg DASH options [here](https://ffmpeg.org/ffmpeg-formats.html#dash-2)) but you can convert your audio file to fragmented mp4 files and add an AUDIO tag line to your manifest file(*.mpd).
