### ISSUE TITLE
[Question] Does the h264_amf codec exist?

### ISSUE THREAD

**Issue by adis0308** [aminyazdanpanah/PHP-FFmpeg-video-streaming#98]
Does the h264_amf video codec exist? Or just a typo?
I found the h264_amf in getAvailableVideoCodecs() in the /Format/X264.php file.

**Comment by aminyazdanpanah** [comment]
Yes. according to [this link](https://stackoverflow.com/questions/50693934/different-h264-encoders-in-ffmpeg), it is fo accessing the AMD GPU, (windows only)
